"use client"

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RUfrQTzdTYV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/


import { useState, useMemo } from "react"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Image from "next/image"

const classes = [
  {
    id: 1,
    image: "/placeholder.svg",
    title: "Introduction to React",
    description: "Learn the fundamentals of React.js in this beginner-friendly classes.",
    category: "Programming",
    date: "2023-06-01",
    price: 49.99,
  },
  {
    id: 2,
    image: "/placeholder.svg",
    title: "Mastering Photoshop",
    description: "Dive deep into the world of Photoshop and unlock your creative potential.",
    category: "Design",
    date: "2023-07-15",
    price: 79.99,
  },
  {
    id: 3,
    image: "/placeholder.svg",
    title: "Public Speaking Essentials",
    description: "Become a confident and engaging public speaker in this interactive webinar.",
    category: "Business",
    date: "2023-08-20",
    price: 59.99,
  },
  {
    id: 4,
    image: "/placeholder.svg",
    title: "Mindfulness for Beginners",
    description: "Explore the transformative power of mindfulness in this introductory class.",
    category: "Health",
    date: "2023-09-01",
    price: 39.99,
  },
  {
    id: 5,
    image: "/placeholder.svg",
    title: "Digital Marketing Strategies",
    description: "Learn effective digital marketing techniques to grow your online presence.",
    category: "Business",
    date: "2023-10-10",
    price: 69.99,
  },
  {
    id: 6,
    image: "/placeholder.svg",
    title: "Intermediate Python Programming",
    description: "Take your Python skills to the next level with this comprehensive course.",
    category: "Programming",
    date: "2023-11-01",
    price: 59.99,
  },
]

export default function Programs() {
  const [searchTerm, setSearchTerm] = useState("")
  const [selectedCategory, setSelectedCategory] = useState("")
  const [selectedDate, setSelectedDate] = useState("")
  const [priceRange, setPriceRange] = useState([0, 100])
  const [viewMode, setViewMode] = useState("grid")

  const filteredClasses = useMemo(() => {
    return classes.filter((item) => {
      const categoryMatch = selectedCategory ? item.category === selectedCategory : true
      const dateMatch = selectedDate ? item.date === selectedDate : true
      const priceMatch = item.price >= priceRange[0] && item.price <= priceRange[1]
      const searchMatch = item.title.toLowerCase().includes(searchTerm.toLowerCase())
      return categoryMatch && dateMatch && priceMatch && searchMatch
    })
  }, [selectedCategory, selectedDate, priceRange, searchTerm])

  return (
    <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Search Classes and Webinars</h1>
        <p className="text-muted-foreground">Find the perfect class or webinar to suit your needs.</p>
      </div>
      <div className="bg-muted rounded-lg p-4 sm:p-6 mb-8">
        <form className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <Label htmlFor="search">Search</Label>
            <Input
              id="search"
              type="text"
              placeholder="Search classes and webinars"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="category">Category</Label>
            <Select value={selectedCategory} onValueChange={setSelectedCategory}>
              <SelectTrigger id="category">
                <SelectValue placeholder="Select a category" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all" className="bg-white">All Categories</SelectItem>
                <SelectItem value="Programming" className="bg-white">Programming</SelectItem>
                <SelectItem value="Design" className="bg-white">Design</SelectItem>
                <SelectItem value="Business" className="bg-white">Business</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="date">Date</Label>
            <Input id="date" type="date" value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)} />
          </div>
          <div>
            <Label htmlFor="sort">Sort By</Label>
            <Select>
              <SelectTrigger id="sort">
                <SelectValue placeholder="Select sorting option" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="relevance" className="bg-white">Relevance</SelectItem>
                <SelectItem value="price-desc" className="bg-white">Popularity</SelectItem>
                <SelectItem value="date-asc" className="bg-white">Date: Oldest First</SelectItem>
                <SelectItem value="date-desc" className="bg-white">Date: Newest First</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </form>
      </div>
      <div className="flex items-center justify-between mb-4">
        <div>
          <Button
            variant={viewMode === "grid" ? "night" : "default"}
            onClick={() => setViewMode("grid")}
            className="mr-2"
          >
            Grid View
          </Button>
          <Button variant={viewMode === "list" ? "night" : "default"} onClick={() => setViewMode("list")}>
            List View
          </Button>
        </div>
      </div>
      {viewMode === "grid" ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredClasses.map((item) => (
            <div key={item.id} className="bg-muted rounded-lg overflow-hidden">
              <Image
                src="/placeholder.svg"
                alt={item.title}
                width={600}
                height={400}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-bold mb-2">{item.title}</h3>
                <p className="text-muted-foreground mb-4">{item.description}</p>
                <div className="flex items-center justify-between">
                  <div className="text-primary font-medium">${item.price}</div>
                  <Button variant="outline">{item.category === "Webinar" ? "Join" : "Learn More"}</Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="space-y-4">
          {filteredClasses.map((item) => (
            <div key={item.id} className="bg-muted rounded-lg overflow-hidden flex">
              <Image
                src="/placeholder.svg"
                alt={item.title}
                width={200}
                height={150}
                className="w-40 h-30 object-cover"
                style={{ aspectRatio: "200/150", objectFit: "cover" }}
              />
              <div className="p-4 flex-1">
                <h3 className="text-lg font-bold mb-2">{item.title}</h3>
                <p className="text-muted-foreground mb-4">{item.description}</p>
                <div className="flex items-center justify-between">
                  <div className="text-primary font-medium">${item.price}</div>
                  <Button variant="outline">{item.category === "Webinar" ? "Join" : "Learn More"}</Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
