/**
 * AES-256-GCM encryption for customer IdP secrets held in `SsoProvider`.
 *
 * ## Why
 *
 * `SsoProvider.oidcConfig` / `SsoProvider.samlConfig` are `String` columns
 * holding JSON that embeds the **customer's** OIDC client secret (and, for
 * SAML, potentially a `privateKey` / `decryptionPvk`). Until now the POST /
 * providers route wrote them with a bare `JSON.stringify`, so a single
 * `psql` dump of the database — or a read-only replica, or a support
 * screenshot of a row — is a full IdP credential compromise for that
 * customer. The repo already encrypts PANs with `PAN_ENCRYPTION_KEY`
 * (`lib/payments/tax/pan-crypto.ts`); this module follows that module's
 * conventions exactly so there is one key-derivation story in the codebase.
 *
 * ## Envelope
 *
 *   sso:v1:<iv_b64url>:<tag_b64url>:<ciphertext_b64url>
 *
 * The `sso:v1:` prefix is the version tag, and it is what makes the format
 * replaceable: a future `sso:v2:` envelope can change the KDF or move to
 * AES-GCM-SIV without a flag day, because `isEncrypted` keys off the prefix
 * and `decryptSecretPayload` dispatches on it. Plaintext rows have no prefix
 * and are passed through untouched (see "Migration path" below).
 *
 * ## Key derivation — mirrors `pan-crypto.ts` deliberately
 *
 * `pan-crypto.ts` does NOT derive anything: it requires `PAN_ENCRYPTION_KEY`
 * to be a 64-character hex string and does `Buffer.from(hex, "hex")` for the
 * raw 32 bytes, generated by `openssl rand -hex 32`. Deriving a key that is
 * already high-entropy random would *reduce* security (it would add a
 * passphrase assumption to a value that has none) and would give the two
 * secrets in this repo different, surprising shapes. So this module takes
 * the env var in the same shape and applies the same validation, and the
 * two modules stay symmetric: same `openssl rand -hex 32` incantation, same
 * 64-hex contract, same 12-byte IV / 16-byte tag parameters.
 *
 * Using a SEPARATE key from `PAN_ENCRYPTION_KEY` is deliberate: rotating
 * consultant tax data must not require re-encrypting every customer's IdP
 * credential, and a PAN-key compromise must not decrypt SSO rows.
 *
 * ## Failure mode
 *
 * A stored value that *looks* like an envelope but cannot be decrypted (key
 * rotated without re-running the migration, truncated column, wrong key
 * mounted) throws {@link SecretPayloadError} rather than returning garbage.
 * The admin settings GET catches it, so an undecryptable config surfaces as
 * a specific `SSO_PROVIDER_MISCONFIGURED` and not as a 500 with an empty
 * body.
 *
 * ## Plaintext rows
 *
 * `decryptSecretPayload` still passes plaintext JSON through unchanged, so a
 * row written without an envelope stays readable.
 *
 * ## Where the read seam lives
 *
 * BetterAuth's own runtime read cannot be given a decrypt hook: its plugin
 * reads the column as
 *
 *   `parsedSamlConfig = typeof c === "object" ? c : safeJsonParse(c)`
 *
 * (`@better-auth/sso@1.6.5` `dist/index.mjs:2375`) with no
 * `SSOOptions` key that intercepts it, and `@better-auth/prisma-adapter`
 * 1.6.5 exposes no transform option either. The seam therefore had to be the
 * database layer, and it is: `lib/prisma-sso-secret-extension.ts` registers a
 * `$extends({ result })` map in `lib/prisma.ts` that runs
 * `decryptSecretPayload` on `SsoProvider.oidcConfig` and `.samlConfig` on
 * every read, and normalises the result to a parsed object. Because it is on
 * the client, *every* reader is covered — BetterAuth's plugin and the admin
 * settings GET — and no caller can forget to decrypt.
 */

import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";

/** AES-256-GCM, matching `lib/payments/tax/pan-crypto.ts`. */
const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12;
const AUTH_TAG_LENGTH = 16;

/**
 * Version tag. Bumping the version (and adding a branch in
 * `decryptSecretPayload`) is the supported way to change this format.
 */
const ENVELOPE_VERSION = "sso:v1";
const ENVELOPE_PREFIX = `${ENVELOPE_VERSION}:`;
/**
 * Parts *after* the `sso:v1:` prefix, i.e. iv, tag, ciphertext. Not 4: the
 * version tag itself contains a colon, so the whole string splits into five
 * and only the three after the prefix are ours.
 */
const ENVELOPE_PARTS = 3;

/**
 * Why a stored value could not be read. `reason` is a closed set so callers
 * can map onto `lib/labels/auth-errors.ts` codes without string-matching a
 * library error message.
 */
export type SecretPayloadFailure =
  /** The key env var is missing or not 64 hex chars — a deployment fault. */
  | "key_unavailable"
  /** Envelope is present but structurally invalid (wrong part count, bad base64url). */
  | "envelope_malformed"
  /** Envelope parsed but the GCM auth tag did not verify — wrong key or tampered ciphertext. */
  | "auth_failed"
  /** Decrypted bytes are not the JSON the caller stored. */
  | "payload_not_json";

export class SecretPayloadError extends Error {
  readonly failure: SecretPayloadFailure;

  constructor(failure: SecretPayloadFailure, detail: string) {
    super(`SSO secret payload unreadable (${failure}): ${detail}`);
    this.name = "SecretPayloadError";
    this.failure = failure;
  }
}

/**
 * 64 hex characters, i.e. 32 raw bytes. One constant so the validating
 * predicate and the throwing reader can never drift into disagreeing about
 * what a well-formed key is.
 */
const KEY_HEX = /^[0-9a-fA-F]{64}$/;

/**
 * Raw 32-byte key from `AUTH_CONFIG_ENCRYPTION_KEY`, validated exactly the
 * way `pan-crypto.ts` validates `PAN_ENCRYPTION_KEY`: 64 hex chars.
 */
function getKey(): Buffer {
  const hex = process.env.AUTH_CONFIG_ENCRYPTION_KEY;
  if (!hex || !KEY_HEX.test(hex)) {
    throw new SecretPayloadError(
      "key_unavailable",
      "AUTH_CONFIG_ENCRYPTION_KEY must be set to a 64-character hex string (32 bytes). " +
        "Generate with: openssl rand -hex 32",
    );
  }
  return Buffer.from(hex, "hex");
}

function encode(buffer: Buffer): string {
  return buffer.toString("base64url");
}

function decode(part: string): Buffer {
  return Buffer.from(part, "base64url");
}

/**
 * True when `stored` is an envelope this module wrote.
 *
 * Deliberately a prefix test and not a "parses as JSON" test: a *plaintext*
 * row is a JSON object, and so is a hypothetical non-envelope format. Only
 * the version tag tells us a value went through {@link encryptSecretPayload}.
 */
export function isEncrypted(stored: string | null | undefined): boolean {
  return typeof stored === "string" && stored.startsWith(ENVELOPE_PREFIX);
}

/**
 * Encrypt a config object for storage in `oidcConfig` / `samlConfig`.
 *
 * The caller stores the returned string verbatim; it is NOT valid JSON, so
 * anything that expects JSON in that column (BetterAuth's own read path) has
 * to run it through {@link decryptSecretPayload} first.
 */
export function encryptSecretPayload(payload: unknown): string {
  const key = getKey();
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const plaintext = Buffer.from(JSON.stringify(payload), "utf8");
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]);

  return [
    ENVELOPE_VERSION,
    encode(iv),
    encode(cipher.getAuthTag()),
    encode(ciphertext),
  ].join(":");
}

/**
 * Read a stored config back.
 *
 * Three-way behaviour, all of it load-bearing:
 *
 *   1. `null` / `undefined` / empty → `null`. A half-written row is a
 *      legitimate "no config", not an error, and the settings routes infer
 *      provider type from whether this column is null.
 *   2. No `sso:v1:` prefix → parsed as plaintext JSON. Every row written
 *      before this module existed is in this state, and they must keep
 *      working. A non-JSON value here is a corrupt legacy row, which is
 *      exactly the `SSO_PROVIDER_MISCONFIGURED` case, not a crash.
 *   3. Prefixed → envelope path. Fails closed via {@link SecretPayloadError}.
 */
export function decryptSecretPayload<T = unknown>(
  stored: string | null | undefined,
): T | null {
  if (stored === null || stored === undefined || stored === "") return null;

  if (!isEncrypted(stored)) {
    // Pre-encryption row: plain JSON, the format the create route has always
    // written. A parse failure here means the column holds garbage.
    try {
      return JSON.parse(stored) as T;
    } catch {
      throw new SecretPayloadError(
        "payload_not_json",
        "stored config is neither an sso:v1 envelope nor JSON",
      );
    }
  }

  const parts = stored.slice(ENVELOPE_PREFIX.length).split(":");
  if (parts.length !== ENVELOPE_PARTS) {
    throw new SecretPayloadError(
      "envelope_malformed",
      `expected ${ENVELOPE_PARTS} envelope parts, found ${parts.length}`,
    );
  }

  const [ivPart, tagPart, ciphertextPart] = parts;
  // `base64url` decoding is lenient, so re-encoding is the cheap way to reject
  // parts that are not actually base64url before handing them to OpenSSL.
  for (const part of [ivPart, tagPart, ciphertextPart]) {
    if (!part || encode(decode(part)) !== part) {
      throw new SecretPayloadError(
        "envelope_malformed",
        "envelope contains a part that is not base64url",
      );
    }
  }

  const iv = decode(ivPart);
  const authTag = decode(tagPart);
  if (iv.length !== IV_LENGTH || authTag.length !== AUTH_TAG_LENGTH) {
    throw new SecretPayloadError(
      "envelope_malformed",
      `expected a ${IV_LENGTH}-byte IV and ${AUTH_TAG_LENGTH}-byte auth tag`,
    );
  }

  // Resolved BEFORE the AEAD block, and outside its try/catch, so that a
  // missing or malformed key keeps its own `key_unavailable` reason instead of
  // being flattened into `auth_failed`.
  //
  // This is load-bearing for every caller, not a tidiness point. All three of
  // them branch on the reason to decide what to tell the operator: a
  // `key_unavailable` means "the server is misconfigured, contact support,
  // re-entering the IdP will not help", while `auth_failed` means "this row
  // needs re-entering". Swallowing the two together sends every admin to
  // rewrite a working IdP config because a Netlify env var is missing.
  //
  // It is placed here rather than at the top of the function so that a
  // *plaintext* row still reads with no key mounted at all — the pre-
  // encryption rows must keep working on a deployment that has never set
  // `AUTH_CONFIG_ENCRYPTION_KEY`, which is the state this repo is in.
  const key = getKey();

  let plaintext: Buffer;
  try {
    const decipher = createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);
    plaintext = Buffer.concat([
      decipher.update(decode(ciphertextPart)),
      decipher.final(),
    ]);
  } catch (err) {
    // `decipher.final()` throws when the tag does not verify — a key that was
    // rotated without re-running the migration, or a tampered column. Both
    // are "we cannot trust this config", and both must reach the caller as
    // SSO_PROVIDER_MISCONFIGURED rather than a 500.
    throw new SecretPayloadError(
      "auth_failed",
      err instanceof Error ? err.message : "GCM authentication failed",
    );
  }

  try {
    return JSON.parse(plaintext.toString("utf8")) as T;
  } catch {
    throw new SecretPayloadError(
      "payload_not_json",
      "decrypted envelope did not contain JSON",
    );
  }
}

/**
 * True when `AUTH_CONFIG_ENCRYPTION_KEY` is present and well-formed.
 *
 * Exists so a caller can decide *before* it starts writing whether encryption
 * is possible at all. Without it the only way to find out is to call
 * {@link encryptSecretPayload} and catch `SecretPayloadError`, which is by
 * then part-way through a write — fine for a one-row update, wrong for a
 * request that is about to create a provider and return 201 with no idea its
 * own config is unencryptable.
 */
export function isEncryptionKeyUsable(): boolean {
  const hex = process.env.AUTH_CONFIG_ENCRYPTION_KEY;
  return typeof hex === "string" && KEY_HEX.test(hex);
}
