/**
 * IRP (Invoice Registration Portal) / IRN (Invoice Reference Number) —
 * INDIA COMPLIANCE STUB.
 *
 * STATUS: stub. Returns `null` IRN so OrganizationInvoice rows can be
 * created but are not yet e-invoice-registered. Live uploader lands in a
 * follow-up PR.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * LIVE IMPLEMENTATION REQUIREMENTS (follow-up PR)
 * ─────────────────────────────────────────────────────────────────────────
 *
 * E-invoicing is MANDATORY for businesses with AATO (Aggregate Annual
 * Turnover) > ₹5 Cr in any prior financial year since 2017-18. Key points:
 *
 *   - IRN must be generated WITHIN 30 DAYS of invoice date for suppliers
 *     with AATO > ₹10 Cr. Missing this window makes the invoice invalid
 *     for ITC claims by the buyer.
 *
 *   - Buyers with AATO > ₹5 Cr will REJECT non-IRN invoices at their AP
 *     systems. Enterprise deals are blocked without IRN.
 *
 *   - IRN is 64 chars, generated by the IRP (currently 10 registered IRPs;
 *     most common: IRIS Business Services, ClearTax, Masters India).
 *
 *   - Response payload includes: IRN, Ack-Number, Ack-Date, Signed-QR-Code
 *     (base64 PNG embedded in invoice PDF). All fields live on
 *     `OrganizationInvoice`.
 *
 * Live impl options:
 *
 *   OPTION A: IRIS Business Services (API-first)
 *     - Connector: https://einv-apisandbox.nic.in (sandbox)
 *     - Authentication: client-cert + API key
 *     - Rate limits: 5000 calls/day in sandbox, higher in prod.
 *     - Cost: ~₹8-10 per IRN.
 *
 *   OPTION B: ClearTax
 *     - REST API wrapper on top of IRP.
 *     - Handles retries and status polling automatically.
 *     - Cost: ~₹15 per IRN, includes reconciliation dashboard.
 *
 *   OPTION C: Direct NIC GSTN API
 *     - Free but rate-limited and requires manual authentication setup.
 *     - Only recommended for very high-volume deployments.
 *
 * Recommended: OPTION B (ClearTax) for MVP — handles retry + status out of
 * the box. Migrate to OPTION A once volume justifies the integration cost.
 *
 * Cron: `jobs/compliance/irp-uploader.ts` runs daily. For every invoice
 * with `irpStatus = PENDING` and `issuedAt within 30 days`:
 *   1. Call IRP.generate(invoicePayload).
 *   2. On success: persist irn, ackNumber, ackDate, signedQrPayload;
 *      set irpStatus=GENERATED, irpUploadedAt=now().
 *   3. On failure: set irpStatus=FAILED; surface in admin dashboard.
 *   4. Never retry generated rows — IRN regeneration requires cancel+reissue.
 *
 * Invoice CANCELLATION (if buyer rejects or dispute):
 *   - Must be cancelled on IRP within 24 hours of generation.
 *   - Set irpStatus=CANCELLED; issue a credit note and new invoice.
 *   - After 24-hour window, only credit note is valid (IRP won't cancel).
 *
 * ─────────────────────────────────────────────────────────────────────────
 */

export interface IrpResponse {
  irn: string | null;
  ackNumber: string | null;
  ackDate: Date | null;
  signedQrPayload: string | null;
  status: "GENERATED" | "FAILED" | "CANCELLED";
  reason: string;
}

/**
 * STUB: Uploads invoice to IRP and returns IRN.
 *
 * TODO: replace with live connector per the header docblock.
 */
export async function generateIrn(_params: {
  invoiceId: string;
  payload: Record<string, unknown>;
}): Promise<IrpResponse> {
  // STUB: returns null IRN; downstream code must treat null as "not yet registered".
  return {
    irn: null,
    ackNumber: null,
    ackDate: null,
    signedQrPayload: null,
    status: "FAILED",
    reason: "STUB: IRP uploader not yet implemented; see lib/compliance/irp.ts TODO",
  };
}

/**
 * STUB: Cancels an IRN on the IRP within 24 hours of generation.
 */
export async function cancelIrn(_params: {
  irn: string;
  reason: string;
}): Promise<{ cancelled: boolean; reason: string }> {
  return {
    cancelled: false,
    reason: "STUB: IRP cancellation not yet implemented",
  };
}
