/**
 * TDS (Tax Deducted at Source) live derivation — INDIA COMPLIANCE.
 *
 * Section selection precedence (CBDT circulars, FY 2025-26):
 *   - Default: Section 194-O (1%) since Familiarise is the e-commerce
 *     operator. Applies to residents AND non-residents on the platform.
 *   - Explicit override: `consultant.tdsSection` is honoured for
 *     consultants whose engagement is direct (not via the platform e.g.
 *     direct-invoice contractors). This pivots between 194-O / 194J / 194C.
 *   - 194-O takes precedence over 194J in mixed-flow cases (platform-
 *     as-intermediary precedence per CBDT).
 *
 * PAN fallback (Section 206AA):
 *   - If `panNumber` is null OR doesn't match /^[A-Z]{5}[0-9]{4}[A-Z]$/,
 *     withhold at the 20% punitive rate. This wins over both DTAA and
 *     section default (it's the higher-of rule).
 *
 * Lower-rate certificate (Section 197):
 *   - If `tdsLowerRateCert` is non-empty AND `tdsRate` is populated,
 *     use the cert's rate (which is taken from `consultant.tdsRate` —
 *     the schema doesn't carry a separate cert-rate column in v1).
 *
 * DTAA rate lookup (NON_RESIDENT only):
 *   - Cross-reference `providerCountry` against `dtaa-rates.json`.
 *   - Apply DTAA rate ONLY if it is strictly LOWER than the section
 *     default. India's TDS framework permits the LOWER of section vs
 *     DTAA — so a treaty rate of 10% never reduces a 1% Section 194-O.
 *   - Captures `dtaaRateApplied` on the Payout when applied; null
 *     otherwise.
 *
 * Removed provisions (DO NOT implement):
 *   - TCS Section 206C(1H): removed 1 Apr 2025.
 *   - Section 206AB (higher TDS for non-filers): omitted 1 Apr 2025.
 *   - Equalisation Levy (2% cross-border, 6% ads): abolished.
 *
 * Reporting: Quarterly TDS returns (Form 26Q / 27Q) generated by batch
 * job, not this lib. This lib only derives the per-payout numbers.
 */

import type { ConsultantProfile } from "@prisma/client";
import dtaaRatesJson from "./dtaa-rates.json";

/** Default rates per section. Update when CBDT changes the rate card. */
export const TDS_SECTION_DEFAULTS: Record<string, number> = {
  "194O": 0.01,
  "194J": 0.1,
  "194C": 0.02,
};

/** Section 206AA punitive rate when PAN is missing or malformed. */
export const PAN_FALLBACK_RATE = 0.2;

/** Default section when none is explicitly set on the consultant. */
export const DEFAULT_SECTION = "194O";

const DTAA_RATES: Record<string, number> =
  (dtaaRatesJson as { rates: Record<string, number> }).rates ?? {};

export interface TdsComputation {
  tdsSection: string; // "194J" | "194O" | "194C"
  tdsRate: number; // decimal (0.10 = 10%)
  tdsAmountPaise: number;
  dtaaRateApplied: number | null;
  fallbackApplied: boolean; // true if 206AA/PAN-missing fallback triggered
  reason: string; // human-readable explanation for audit log
}

/**
 * The minimal shape `computeTdsForPayout` needs from a consultant. Lifted
 * out of `Pick<ConsultantProfile, ...>` so non-Prisma callers (synthetic
 * inputs from `OrganizationPayout` paths that don't carry a per-consultant
 * FK) can pass a structurally compatible object.
 */
export type TdsConsultantInput = {
  panNumber: string | null;
  residencyStatus: ConsultantProfile["residencyStatus"];
  tdsSection: string | null;
  tdsRate: number | null;
  tdsLowerRateCert: string | null;
  providerCountry: string | null;
};

/**
 * Validates PAN format. PAN is exactly: 5 letters + 4 digits + 1 letter,
 * uppercase only. Used for Section 206AA fallback.
 */
export function isValidPan(pan: string | null | undefined): boolean {
  if (!pan) return false;
  return /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan);
}

function decimalToNumber(value: number | null | undefined): number | null {
  if (value === null || value === undefined) return null;
  return value;
}

/**
 * Compute TDS for a payout to a consultant. Pure function — no side
 * effects, no DB reads. Caller passes in the consultant's tax fields.
 */
export function computeTdsForPayout(params: {
  grossAmountPaise: number;
  consultant: TdsConsultantInput;
}): TdsComputation {
  const { grossAmountPaise, consultant } = params;
  const reasons: string[] = [];

  // --- 1. Section selection
  const explicitSection = consultant.tdsSection ?? null;
  const tdsSection = explicitSection ?? DEFAULT_SECTION;
  const sectionDefaultRate =
    TDS_SECTION_DEFAULTS[tdsSection] ?? TDS_SECTION_DEFAULTS[DEFAULT_SECTION];
  if (explicitSection) {
    reasons.push(`section=${tdsSection} (explicit override)`);
  } else {
    reasons.push(`section=${tdsSection} (platform default)`);
  }

  // --- 2. PAN fallback (Section 206AA) — wins over everything else.
  if (!isValidPan(consultant.panNumber)) {
    const amt = Math.floor(grossAmountPaise * PAN_FALLBACK_RATE);
    reasons.push("Section 206AA fallback (PAN missing or malformed) → 20%");
    return {
      tdsSection,
      tdsRate: PAN_FALLBACK_RATE,
      tdsAmountPaise: amt,
      dtaaRateApplied: null,
      fallbackApplied: true,
      reason: reasons.join("; "),
    };
  }

  // --- 3. Section 197 lower-rate certificate — overrides section default
  // when both the cert ref AND a per-consultant rate are populated. The
  // schema doesn't carry a separate `tdsLowerRateCertRate` field, so we
  // re-purpose `consultant.tdsRate` as the cert's rate.
  const certRate = decimalToNumber(consultant.tdsRate);
  if (consultant.tdsLowerRateCert && certRate !== null) {
    const amt = Math.floor(grossAmountPaise * certRate);
    reasons.push(`Section 197 cert ${consultant.tdsLowerRateCert} → ${(certRate * 100).toFixed(2)}%`);
    return {
      tdsSection,
      tdsRate: certRate,
      tdsAmountPaise: amt,
      dtaaRateApplied: null,
      fallbackApplied: false,
      reason: reasons.join("; "),
    };
  }

  // --- 4. DTAA lookup (NON_RESIDENT only)
  let effectiveRate = sectionDefaultRate;
  let dtaaRateApplied: number | null = null;
  if (consultant.residencyStatus === "NON_RESIDENT") {
    const country = (consultant.providerCountry ?? "").toUpperCase();
    const dtaaRate = country ? DTAA_RATES[country] : undefined;
    if (dtaaRate === undefined) {
      reasons.push(`no DTAA entry for country=${country || "(none)"}`);
    } else if (dtaaRate < sectionDefaultRate) {
      effectiveRate = dtaaRate;
      dtaaRateApplied = dtaaRate;
      reasons.push(
        `DTAA ${country} ${(dtaaRate * 100).toFixed(2)}% applied (lower than section ${(sectionDefaultRate * 100).toFixed(2)}%)`,
      );
    } else {
      reasons.push(
        `DTAA ${country} ${(dtaaRate * 100).toFixed(2)}% NOT lower than section default ${(sectionDefaultRate * 100).toFixed(2)}% — section wins`,
      );
    }
  }

  const tdsAmountPaise = Math.floor(grossAmountPaise * effectiveRate);
  return {
    tdsSection,
    tdsRate: effectiveRate,
    tdsAmountPaise,
    dtaaRateApplied,
    fallbackApplied: false,
    reason: reasons.join("; "),
  };
}
