/**
 * TDS (Tax Deducted at Source) derivation — INDIA COMPLIANCE STUB.
 *
 * STATUS: stub. Returns sensible defaults so downstream code doesn't null-
 * crash. Live derivation lands in a follow-up PR.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * LIVE IMPLEMENTATION REQUIREMENTS (follow-up PR)
 * ─────────────────────────────────────────────────────────────────────────
 *
 * 1. Section selection precedence (consult current CBDT circulars):
 *      - If consultant is sourced via e-commerce operator platform (i.e.
 *        Familiarise itself): Section 194-O (1% TDS) applies.
 *      - If consultant provides professional services to a deductor
 *        (Familiarise): Section 194J (10% TDS on fees for professional
 *        services).
 *      - If relationship is pure contractor without professional services:
 *        Section 194C (1-2% TDS).
 *      - 194-O generally overrides 194J in mixed-flow cases (platform-as-
 *        intermediary precedence). Verify the circular before coding.
 *
 * 2. PAN fallback (Section 206AA):
 *      - If `consultantProfile.panNumber` is null or invalid format (not
 *        10 chars matching /[A-Z]{5}[0-9]{4}[A-Z]/), apply 20% TDS (the
 *        higher of 20% vs section rate).
 *
 * 3. Lower-rate certificate (Section 197):
 *      - If `consultantProfile.tdsLowerRateCert` is populated and valid,
 *        apply the certificate's rate instead of the section default.
 *
 * 4. DTAA rate lookup (for NON_RESIDENT consultants):
 *      - Cross-reference `providerCountry` + tax treaty schedule.
 *      - If DTAA rate < 194J/194O rate, apply DTAA rate and capture
 *        `dtaaRateApplied` on the Payout row.
 *      - Requires Form 10F declaration + Tax Residency Certificate (TRC)
 *        from the consultant. Both kept off-schema in v1; add fields later
 *        if audit demands.
 *
 * 5. Removed provisions (DO NOT implement):
 *      - TCS Section 206C(1H): removed 1 Apr 2025.
 *      - Section 206AB (higher TDS for non-filers): omitted 1 Apr 2025.
 *      - Equalisation Levy (2% cross-border, 6% ads): abolished.
 *
 * 6. Reporting: Quarterly TDS returns (Form 26Q / 27Q) generated by batch
 *    job, not this lib. This lib only derives the per-payout numbers.
 *
 * ─────────────────────────────────────────────────────────────────────────
 */

import type { ConsultantProfile } from "@prisma/client";

export interface TdsComputation {
  tdsSection: string; // "194J" | "194O" | "194C"
  tdsRate: number; // decimal (0.10 = 10%)
  tdsAmountPaise: number;
  dtaaRateApplied: number | null;
  fallbackApplied: boolean; // true if 206AA/PAN-missing fallback triggered
  reason: string; // human-readable explanation for audit log
}

/**
 * STUB: Computes TDS for a payout to a consultant.
 *
 * @param params.grossAmountPaise - Gross amount before TDS, in paise
 * @param params.consultant - ConsultantProfile row (reads panNumber,
 *   residencyStatus, tdsSection, tdsRate, tdsLowerRateCert, providerCountry)
 * @returns TdsComputation with sensible defaults.
 *
 * TODO: replace with live derivation per the header docblock.
 */
export function computeTdsForPayout(params: {
  grossAmountPaise: number;
  consultant: Pick<
    ConsultantProfile,
    | "panNumber"
    | "residencyStatus"
    | "tdsSection"
    | "tdsRate"
    | "tdsLowerRateCert"
    | "providerCountry"
  >;
}): TdsComputation {
  // STUB: 10% flat 194J default; zero paise withheld until live impl.
  const stubRate = 0.1;
  return {
    tdsSection: params.consultant.tdsSection ?? "194J",
    tdsRate: Number(params.consultant.tdsRate ?? stubRate),
    tdsAmountPaise: 0, // stub — do not withhold
    dtaaRateApplied: null,
    fallbackApplied: !params.consultant.panNumber,
    reason: "STUB: TDS derivation deferred; see lib/compliance/tds.ts TODO",
  };
}

/**
 * STUB: Validates PAN format. Real impl checks /[A-Z]{5}[0-9]{4}[A-Z]/.
 */
export function isValidPan(pan: string | null | undefined): boolean {
  if (!pan) return false;
  return /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan);
}
