import { z } from "zod";

import { parseJsonResponse } from "@/lib/fetch-helpers";
import type { Tone } from "@/lib/ui/tone";

// Zod schemas narrow API responses at the network boundary so the panels can
// rely on inferred types instead of `as` casts.

export const billingSummarySchema = z.object({
  // #1427/#1430 — resolved server-side next to the account read; see
  // app/api/organizations/[orgId]/billing/route.ts.
  walletFrozen: z.boolean().default(false),
  walletFrozenReason: z.string().nullable().default(null),
  dunningSuspended: z.boolean().default(false),
  dunningSuspendedInvoiceNumber: z.string().nullable().default(null),
  fundingSource: z
    .enum(["PERSONAL", "WALLET", "INVOICE", "LICENSE"])
    .nullable(),
  monthToDate: z.object({
    gross: z.number(),
    paymentCount: z.number(),
  }),
  outstanding: z.object({
    amount: z.number(),
    invoiceCount: z.number(),
  }),
  // #777 §B: INVOICE-funded credit ceiling (paise; null/absent = unlimited).
  creditLimitPaise: z.number().nullable().optional(),
  pendingCharges: z
    .object({ amount: z.number(), paymentCount: z.number() })
    .nullable(),
  paymentTermsDays: z.number(),
  licenseContract: z
    .object({
      id: z.string(),
      effectiveFrom: z.string(),
      effectiveTo: z.string().nullable(),
      autoRenew: z.boolean(),
      subscription: z
        .object({
          model: z.enum(["PER_SEAT", "FLAT_FEE"]),
          cycle: z.enum(["MONTHLY", "QUARTERLY", "ANNUAL"]),
          flatFeePaise: z.number().nullable(),
          currentCycleStart: z.string(),
          currentCycleEnd: z.string(),
          nextInvoiceDate: z.string(),
        })
        .nullable(),
    })
    .nullable(),
});
export type BillingSummary = z.infer<typeof billingSummarySchema>;

const invoiceStatusSchema = z.enum([
  "DRAFT",
  "ISSUED",
  "PAID",
  "OVERDUE",
  "VOID",
  "CANCELLED",
]);
export type OrgInvoiceStatus = z.infer<typeof invoiceStatusSchema>;

/** #1762-4 — one label + tone per invoice state, from the org's side. */
export const INVOICE_STATUS: Record<
  OrgInvoiceStatus,
  { label: string; tone: Tone }
> = {
  DRAFT: { label: "Draft", tone: "neutral" },
  ISSUED: { label: "Due", tone: "warning" },
  PAID: { label: "Paid", tone: "success" },
  OVERDUE: { label: "Overdue", tone: "critical" },
  VOID: { label: "Void", tone: "neutral" },
  CANCELLED: { label: "Cancelled", tone: "neutral" },
};

const orgInvoiceSchema = z.object({
  id: z.string(),
  invoiceNumber: z.string(),
  totalPaise: z.number(),
  displayCurrency: z.string(),
  status: invoiceStatusSchema,
  dueDate: z.string().nullable(),
  paidAt: z.string().nullable(),
  autoGenerated: z.boolean(),
  createdAt: z.string(),
});
export type OrgInvoice = z.infer<typeof orgInvoiceSchema>;

const invoicesListResponseSchema = z.object({
  data: z.array(orgInvoiceSchema).default([]),
});

const invoicePayResponseSchema = z.object({
  razorpayOrderId: z.string().startsWith("order_"),
  keyId: z.string().min(1),
  amountPaise: z.number().int().positive(),
  currency: z.string().length(3),
  invoice: z.object({
    id: z.string(),
    invoiceNumber: z.string(),
    status: z.string(),
  }),
});
export type InvoicePayResponse = z.infer<typeof invoicePayResponseSchema>;

// The detail GET returns the full invoice; the sheet reads only these fields
// and zod strips the rest (the post-checkout poll reads `status` alone).
const invoiceDetailSchema = z.object({
  invoice: z.object({
    id: z.string(),
    invoiceNumber: z.string(),
    status: invoiceStatusSchema,
    displayCurrency: z.string(),
    subtotalPaise: z.number(),
    igstPaise: z.number(),
    cgstPaise: z.number(),
    sgstPaise: z.number(),
    totalPaise: z.number(),
    issuedAt: z.string().nullable(),
    dueDate: z.string().nullable(),
    paidAt: z.string().nullable(),
    billingCycleStart: z.string().nullable(),
    billingCycleEnd: z.string().nullable(),
    purchaseOrder: z.object({ poNumber: z.string() }).nullable().optional(),
    lineItems: z
      .array(
        z.object({
          id: z.string(),
          description: z.string(),
          quantity: z.number(),
          unitPricePaise: z.number(),
        }),
      )
      .default([]),
    creditNotes: z
      .array(
        z.object({
          id: z.string(),
          creditNoteNumber: z.string(),
          totalPaise: z.number(),
          issuedAt: z.string().nullable(),
          reason: z.string().nullable(),
        }),
      )
      .default([]),
  }),
});
export type OrgInvoiceDetail = z.infer<typeof invoiceDetailSchema>["invoice"];

export async function fetchBilling(orgId: string): Promise<BillingSummary> {
  const res = await fetch(`/api/organizations/${orgId}/billing`);
  return parseJsonResponse(
    res,
    billingSummarySchema,
    "Failed to load billing summary",
  );
}

export async function fetchInvoices(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices?perPage=50`,
  );
  const parsed = await parseJsonResponse(
    res,
    invoicesListResponseSchema,
    "Failed to load invoices",
  );
  return { invoices: parsed.data };
}

export function invoiceDetailUrl(orgId: string, invoiceId: string): string {
  return `/api/organizations/${orgId}/billing-account/invoices/${invoiceId}`;
}

export async function fetchInvoiceDetail(
  orgId: string,
  invoiceId: string,
): Promise<OrgInvoiceDetail> {
  const res = await fetch(invoiceDetailUrl(orgId, invoiceId));
  const parsed = await parseJsonResponse(
    res,
    invoiceDetailSchema,
    "Failed to load the invoice",
  );
  return parsed.invoice;
}

export async function payInvoice(
  orgId: string,
  invoiceId: string,
): Promise<InvoicePayResponse> {
  const res = await fetch(`${invoiceDetailUrl(orgId, invoiceId)}/pay`, {
    method: "POST",
  });
  return parseJsonResponse(
    res,
    invoicePayResponseSchema,
    "Failed to initiate payment",
  );
}

const invoiceStatusPollSchema = z.object({
  invoice: z.object({ status: invoiceStatusSchema }),
});

// Same poll budget as the wallet flow — 20s total, then fall back to
// "awaiting confirmation" so the UI never stalls on a slow webhook.
const INVOICE_POLL_INTERVAL_MS = 1000;
const INVOICE_POLL_MAX_ATTEMPTS = 20;

async function fetchInvoiceStatus(
  orgId: string,
  invoiceId: string,
): Promise<OrgInvoiceStatus | null> {
  const res = await fetch(invoiceDetailUrl(orgId, invoiceId));
  if (!res.ok) return null;
  // Tolerate a transient contract-drift parse failure rather than throwing
  // the loop — worst case we keep polling until the budget elapses.
  const parsed = invoiceStatusPollSchema.safeParse(await res.json());
  return parsed.success ? parsed.data.invoice.status : null;
}

/**
 * Poll until the webhook flips the invoice to PAID or the budget elapses. The
 * webhook handler is the source of truth; this only stops the UI lying for
 * the ~5–20s after a successful capture.
 */
export async function pollInvoiceUntilPaid(
  orgId: string,
  invoiceId: string,
): Promise<boolean> {
  for (let attempt = 0; attempt < INVOICE_POLL_MAX_ATTEMPTS; attempt++) {
    const status = await fetchInvoiceStatus(orgId, invoiceId);
    if (status === "PAID") return true;
    await new Promise((r) => setTimeout(r, INVOICE_POLL_INTERVAL_MS));
  }
  return false;
}

// Whole days an OVERDUE invoice is past its due date (createdAt when there is
// none). Ceiled so a freshly-flipped row reads "1 day late", never "0".
export function daysLate(dueDate: string | null, createdAt: string): number {
  const ref = new Date(dueDate ?? createdAt).getTime();
  const diffMs = Date.now() - ref;
  if (diffMs <= 0) return 0;
  return Math.ceil(diffMs / (24 * 60 * 60 * 1000));
}
