"use client";

import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, AlertCircle, Sparkles, Plus, Trash2, Lock } from "lucide-react";
import { z } from "zod";

import { useOrgRole, useRequireOrgAccess } from "../useOrgRole";
import {
  fetchOrgDetails,
  orgDetailsQueryKey,
} from "@/lib/api/organizations/org-details";
import { useToast } from "@/hooks/use-toast";
import { loadScript } from "@/app/checkout/plans/utils";
import {
  errorMessageFromBody,
  parseJsonResponse,
} from "@/lib/fetch-helpers";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

import {
  DashboardHeader,
  DashboardContent,
  DashboardGrid,
} from "@/components/dashboard/DashboardShell";
import { StatCard } from "@/components/dashboard/StatCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { formatCurrencyAmount } from "@/utils/formatting";
import { FUNDING_SOURCE_LABEL } from "@/lib/labels/org-labels";
import { useSession } from "@/lib/auth-client";
import { buildRazorpayPrefill } from "@/lib/payments/razorpay-prefill";
import { WalletTab } from "./WalletTab";

// ---------------------------------------------------------------------------
// Zod schemas — narrow API responses at the network boundary so the rest
// of the component can rely on inferred types instead of `as` casts.
// ---------------------------------------------------------------------------

const billingSummarySchema = z.object({
  fundingSource: z
    .enum(["PERSONAL", "WALLET", "INVOICE", "LICENSE"])
    .nullable(),
  monthToDate: z.object({
    gross: z.number(),
    paymentCount: z.number(),
  }),
  outstanding: z.object({
    amount: z.number(),
    invoiceCount: z.number(),
  }),
  // #777 §B: INVOICE-funded credit ceiling (paise; null/absent = unlimited).
  // Optional so the client tolerates the API until it ships the field —
  // when absent we treat the org as unlimited rather than inventing a cap.
  creditLimitPaise: z.number().nullable().optional(),
  pendingCharges: z
    .object({ amount: z.number(), paymentCount: z.number() })
    .nullable(),
  paymentTermsDays: z.number(),
  licenseContract: z
    .object({
      id: z.string(),
      effectiveFrom: z.string(),
      effectiveTo: z.string().nullable(),
      autoRenew: z.boolean(),
      subscription: z
        .object({
          model: z.enum(["PER_SEAT", "FLAT_FEE"]),
          cycle: z.enum(["MONTHLY", "QUARTERLY", "ANNUAL"]),
          flatFeePaise: z.number().nullable(),
          currentCycleStart: z.string(),
          currentCycleEnd: z.string(),
          nextInvoiceDate: z.string(),
        })
        .nullable(),
    })
    .nullable(),
});
type BillingSummary = z.infer<typeof billingSummarySchema>;

const orgInvoiceSchema = z.object({
  id: z.string(),
  invoiceNumber: z.string(),
  totalPaise: z.number(),
  displayCurrency: z.string(),
  status: z.enum([
    "DRAFT",
    "ISSUED",
    "PAID",
    "OVERDUE",
    "VOID",
    "CANCELLED",
  ]),
  dueDate: z.string().nullable(),
  paidAt: z.string().nullable(),
  autoGenerated: z.boolean(),
  createdAt: z.string(),
});

const invoicesListResponseSchema = z.object({
  data: z.array(orgInvoiceSchema).default([]),
});

const invoicePayResponseSchema = z.object({
  razorpayOrderId: z.string().startsWith("order_"),
  keyId: z.string().min(1),
  amountPaise: z.number().int().positive(),
  currency: z.string().length(3),
  invoice: z.object({
    id: z.string(),
    invoiceNumber: z.string(),
    status: z.string(),
  }),
});
type InvoicePayResponse = z.infer<typeof invoicePayResponseSchema>;

// The per-invoice GET endpoint returns the full invoice + relations,
// but for the post-checkout poll we only care about `status`. Zod
// strips unknown fields by default so this narrow schema accepts the
// full payload and just lifts the one field we need.
const invoiceStatusPollSchema = z.object({
  invoice: z.object({
    status: z.enum([
      "DRAFT",
      "ISSUED",
      "PAID",
      "OVERDUE",
      "VOID",
      "CANCELLED",
    ]),
  }),
});

// Same poll budget as the wallet flow (see credits/page.tsx) — 20s
// total, then we fall back to "awaiting confirmation" so the UI never
// stalls if Razorpay's webhook is slow.
const INVOICE_POLL_INTERVAL_MS = 1000;
const INVOICE_POLL_MAX_ATTEMPTS = 20;

// Discriminated union for the post-checkout flow:
//   - "confirmed": webhook landed within the poll budget; row is PAID.
//   - "pending":   capture succeeded but the webhook is slow.
//   - "not_paid":  popup dismissed or `payment.failed` fired (already
//      toasted); the success handler stays silent.
type InvoicePayMutationResult =
  | { result: InvoicePayResponse; outcome: "confirmed" }
  | { result: InvoicePayResponse; outcome: "pending" }
  | { result: InvoicePayResponse; outcome: "not_paid" };

async function fetchBilling(orgId: string): Promise<BillingSummary> {
  const res = await fetch(`/api/organizations/${orgId}/billing`);
  return parseJsonResponse(
    res,
    billingSummarySchema,
    "Failed to load billing summary",
  );
}

async function fetchInvoices(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices?perPage=50`,
  );
  const parsed = await parseJsonResponse(
    res,
    invoicesListResponseSchema,
    "Failed to load invoices",
  );
  return { invoices: parsed.data };
}

async function generateInvoice(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing/generate-invoice`,
    { method: "POST" },
  );
  const body = await res.json().catch(() => null);
  if (!res.ok) throw new Error(errorMessageFromBody(body, "Failed to generate invoice"));
  return body;
}

async function payInvoice(
  orgId: string,
  invoiceId: string,
): Promise<InvoicePayResponse> {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices/${invoiceId}/pay`,
    { method: "POST" },
  );
  return parseJsonResponse(
    res,
    invoicePayResponseSchema,
    "Failed to initiate payment",
  );
}

async function fetchInvoiceStatus(
  orgId: string,
  invoiceId: string,
): Promise<"DRAFT" | "ISSUED" | "PAID" | "OVERDUE" | "VOID" | "CANCELLED" | null> {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices/${invoiceId}`,
  );
  if (!res.ok) return null;
  // Status poll runs in a tight loop; tolerate a transient
  // contract-drift parse failure rather than throwing the loop —
  // worst case we keep polling until the budget elapses.
  const parsed = invoiceStatusPollSchema.safeParse(await res.json());
  return parsed.success ? parsed.data.invoice.status : null;
}

/**
 * Poll the invoice endpoint until the webhook flips `status` to
 * `PAID` or the budget elapses. Returns `true` on confirmation,
 * `false` on timeout. The webhook handler (`handleOrgPaymentSuccess`)
 * is the source of truth — this exists purely so the UI doesn't lie
 * about state for ~5–20s after a successful capture.
 */
async function pollInvoiceUntilPaid(
  orgId: string,
  invoiceId: string,
): Promise<boolean> {
  for (let attempt = 0; attempt < INVOICE_POLL_MAX_ATTEMPTS; attempt++) {
    const status = await fetchInvoiceStatus(orgId, invoiceId);
    if (status === "PAID") return true;
    await new Promise((r) => setTimeout(r, INVOICE_POLL_INTERVAL_MS));
  }
  return false;
}

// FDE: whole days an OVERDUE invoice is past its dueDate (falling back to
// createdAt when dueDate is null). Floored, min 0 — a freshly-flipped row
// reads "1 day late", never a negative.
function daysLate(dueDate: string | null, createdAt: string): number {
  const ref = new Date(dueDate ?? createdAt).getTime();
  const diffMs = Date.now() - ref;
  return Math.max(0, Math.floor(diffMs / (24 * 60 * 60 * 1000)));
}

export function BillingPageClient({ orgId }: { orgId: string }) {
  const { isAtLeast } = useOrgRole(orgId);
  const { allowed } = useRequireOrgAccess(orgId, {
    minRole: "MANAGER",
    canSponsor: true,
  });
  const searchParams = useSearchParams();
  const initialTab = searchParams?.get("tab") === "wallet" ? "wallet" : "invoices";
  const { data: session } = useSession();
  const queryClient = useQueryClient();

  const summary = useQuery({
    queryKey: ["org-billing", orgId],
    queryFn: () => fetchBilling(orgId),
    // Gate on role+capability so non-billable or non-MANAGER users
    // don't trigger a 403 before the redirect.
    enabled: allowed,
  });
  const invoices = useQuery({
    queryKey: ["org-billing-invoices", orgId],
    queryFn: () => fetchInvoices(orgId),
    enabled: allowed,
  });

  // #779 §B: read org status off the shared org-details cache (the layout
  // already fetched it) to drive the money-move affordance below. The
  // server still rejects top-up/pay when status !== ACTIVE; this just
  // stops the button being a dead click.
  const orgDetails = useQuery({
    queryKey: orgDetailsQueryKey(orgId),
    queryFn: () => fetchOrgDetails(orgId),
    staleTime: 60_000,
  });
  const orgStatus = orgDetails.data?.organization.status;
  const moneyMoveBlocked =
    orgStatus === "PENDING_VERIFICATION" || orgStatus === "SUSPENDED";
  const moneyMoveReason =
    orgStatus === "SUSPENDED"
      ? "Organization suspended"
      : "Verify your organization to move money";

  const generateMutation = useMutation({
    mutationFn: () => generateInvoice(orgId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["org-billing", orgId] });
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
    },
  });

  const { toast } = useToast();

  const payMutation = useMutation({
    mutationFn: async (
      invoiceId: string,
    ): Promise<InvoicePayMutationResult> => {
      const result = await payInvoice(orgId, invoiceId);

      const loaded = await loadScript(
        "https://checkout.razorpay.com/v1/checkout.js",
      ).catch(() => false);
      if (!loaded || !window.Razorpay) {
        throw new Error(
          "Razorpay checkout failed to load. Please disable ad-blockers and retry.",
        );
      }

      // The popup resolves with `paid: true` only if Razorpay's
      // `handler` fired (capture succeeded). Otherwise we treat the
      // attempt as not-yet-paid and skip polling — the row stays
      // ISSUED, no false "awaiting confirmation" toast.
      const prefill = buildRazorpayPrefill({
        name: session?.user?.name ?? null,
        email: session?.user?.email ?? null,
        phone: session?.user?.phone ?? null,
      });
      const paid = await new Promise<boolean>((resolve) => {
        const rzp = new window.Razorpay({
          key: result.keyId,
          amount: result.amountPaise,
          currency: result.currency,
          name: "Familiarise",
          description: `Invoice ${result.invoice.invoiceNumber}`,
          order_id: result.razorpayOrderId,
          ...(Object.keys(prefill).length > 0 ? { prefill } : {}),
          handler: () => {
            resolve(true);
          },
          theme: { color: "#2563EB" },
        });
        rzp.on("payment.failed", () => {
          toast({
            title: "Payment failed",
            description:
              "Your card was declined or the payment timed out. Please try again.",
            variant: "destructive",
          });
          resolve(false);
        });
        rzp.open();
      });

      if (!paid) {
        // Either payment.failed fired (already toasted) or the user
        // dismissed the popup. Skip polling and let the caller show
        // nothing extra.
        return { result, outcome: "not_paid" };
      }

      // Bridge the webhook-settlement race so the row flips to PAID
      // without the user manually refreshing. `outcome === "pending"`
      // means the budget elapsed; the capture is still safe (webhook
      // is idempotent on `OrganizationInvoice.providerOrderId`).
      const confirmed = await pollInvoiceUntilPaid(orgId, invoiceId);
      return { result, outcome: confirmed ? "confirmed" : "pending" };
    },
    onSuccess: ({ result, outcome }) => {
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
      queryClient.invalidateQueries({
        queryKey: ["org-billing", orgId],
      });
      if (outcome === "confirmed") {
        toast({
          title: "Invoice paid",
          description: `Invoice ${result.invoice.invoiceNumber} is now marked as PAID.`,
        });
      } else if (outcome === "pending") {
        toast({
          title: "Payment received",
          description:
            "Awaiting confirmation from Razorpay. The invoice will flip to PAID once the webhook lands.",
        });
      }
      // outcome === "not_paid" — payment.failed already toasted, or
      // the user dismissed the popup; stay silent.
    },
    onError: (err) => {
      toast({
        title: "Payment could not be initiated",
        description: err instanceof Error ? err.message : String(err),
        variant: "destructive",
      });
    },
  });

  // Manual invoice composer state
  const [showComposer, setShowComposer] = useState(false);
  const [lineItems, setLineItems] = useState([
    { description: "", quantity: 1, unitPrice: "" },
  ]);
  const [taxRate, setTaxRate] = useState("");
  const [gstin, setGstin] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [composerError, setComposerError] = useState<string | null>(null);

  if (!allowed) return null;

  async function createInvoice() {
    setComposerError(null);
    const items = lineItems
      .filter((li) => li.description.trim())
      .map((li) => ({
        description: li.description.trim(),
        quantity: li.quantity,
        unitPrice: Math.round(parseFloat(li.unitPrice || "0") * 100),
      }));
    if (items.length === 0) {
      setComposerError("Add at least one line item.");
      return;
    }
    const res = await fetch(`/api/organizations/${orgId}/billing-account/invoices`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        items,
        // Default due date: 60 days from today (NET-60) if not supplied.
        dueDate: dueDate || new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        issueImmediately: true,
      }),
    });
    const body = await res.json();
    if (!res.ok) {
      setComposerError(errorMessageFromBody(body, "Failed to create invoice"));
      return;
    }
    queryClient.invalidateQueries({ queryKey: ["org-billing-invoices", orgId] });
    setShowComposer(false);
    setLineItems([{ description: "", quantity: 1, unitPrice: "" }]);
  }

  return (
    <>
      <DashboardHeader
        title="Billing"
        subtitle="Invoices, charges, and outstanding balance"
        actions={
          <div className="flex gap-2">
            {isAtLeast("OWNER") && (
              <Button size="sm" variant="outline" onClick={() => setShowComposer(true)}>
                <Plus className="h-4 w-4 mr-1" /> Create invoice
              </Button>
            )}
            {isAtLeast("OWNER") &&
              summary.data?.fundingSource === "INVOICE" && (
              <Button
                size="sm"
                onClick={() => generateMutation.mutate()}
                disabled={generateMutation.isPending}
              >
                <Sparkles className="h-4 w-4 mr-1" /> Generate invoice
              </Button>
            )}
          </div>
        }
      />
      <DashboardContent>
        <Tabs defaultValue={initialTab}>
          <TabsList>
            <TabsTrigger value="invoices">Invoices</TabsTrigger>
            <TabsTrigger value="wallet">Wallet</TabsTrigger>
          </TabsList>

          <TabsContent value="invoices" className="space-y-6">
            {/* Annual License panel — surfaces the LICENSE commercial
                value (fee, cycle, renewal, auto-renew) that the
                contract create flow (T5 / #756 GS-1) captures into
                BillingSubscription. Renders only when funding=LICENSE
                AND a subscription has been recorded; LICENSE orgs
                without a subscription see no panel (the contract was
                created with the fee field skipped). */}
            {summary.data?.fundingSource === "LICENSE" &&
              summary.data.licenseContract?.subscription && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base">Annual License</CardTitle>
                    <CardDescription>
                      Pre-paid flat-fee contract. Bookings under this
                      org consume no per-session charge — they&apos;re
                      covered by this license.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3 text-sm">
                      <div>
                        <dt className="text-zinc-500">Fee</dt>
                        <dd className="font-medium">
                          {/* FDE: a fee-less LICENSE contract is incomplete,
                              not free — say so rather than rendering ₹0.00
                              which reads as "no charge". Required by renewal. */}
                          {summary.data.licenseContract.subscription.flatFeePaise ==
                          null ? (
                            <span className="text-amber-600">
                              (fee not recorded){" "}
                              <span className="text-xs font-normal text-zinc-400">
                                — required before renewal
                              </span>
                            </span>
                          ) : (
                            <>
                              {formatCurrencyAmount(
                                summary.data.licenseContract.subscription.flatFeePaise,
                                "INR",
                              )}{" "}
                              / {summary.data.licenseContract.subscription.cycle.toLowerCase()}
                            </>
                          )}
                        </dd>
                      </div>
                      <div>
                        <dt className="text-zinc-500">Current cycle</dt>
                        <dd className="font-medium">
                          {new Date(
                            summary.data.licenseContract.subscription.currentCycleStart,
                          ).toLocaleDateString("en-IN", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}{" "}
                          →{" "}
                          {new Date(
                            summary.data.licenseContract.subscription.currentCycleEnd,
                          ).toLocaleDateString("en-IN", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}
                        </dd>
                      </div>
                      <div>
                        <dt className="text-zinc-500">Next renewal</dt>
                        <dd className="font-medium">
                          {new Date(
                            summary.data.licenseContract.subscription.nextInvoiceDate,
                          ).toLocaleDateString("en-IN", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}
                        </dd>
                      </div>
                      <div>
                        <dt className="text-zinc-500">Auto-renew</dt>
                        <dd className="font-medium">
                          {summary.data.licenseContract.autoRenew
                            ? "Enabled"
                            : "Disabled"}
                        </dd>
                      </div>
                    </dl>
                  </CardContent>
                </Card>
              )}
            {summary.isLoading ? (
              <p className="text-sm text-zinc-500">Loading…</p>
            ) : (
              <DashboardGrid columns={4}>
                <StatCard
                  title="This month gross"
                  value={formatCurrencyAmount(
                    summary.data?.monthToDate.gross ?? 0,
                    "INR",
                  )}
                  subtitle={`${summary.data?.monthToDate.paymentCount ?? 0} bookings`}
                  icon={CreditCard}
                  variant="success"
                />
                <StatCard
                  title="Outstanding"
                  value={formatCurrencyAmount(
                    summary.data?.outstanding.amount ?? 0,
                    "INR",
                  )}
                  subtitle={`${summary.data?.outstanding.invoiceCount ?? 0} invoices`}
                  icon={AlertCircle}
                  variant={
                    (summary.data?.outstanding.invoiceCount ?? 0) > 0
                      ? "warning"
                      : "default"
                  }
                />
                {summary.data?.pendingCharges && (
                  <StatCard
                    title="Pending charges"
                    value={formatCurrencyAmount(
                      summary.data.pendingCharges.amount,
                      "INR",
                    )}
                    subtitle={`${summary.data.pendingCharges.paymentCount} unbilled`}
                    icon={CreditCard}
                  />
                )}
                {/* Payment terms only apply to INVOICE-funded orgs.
                    WALLET orgs pre-fund their balance, LICENSE orgs pay
                    a flat fee — neither has NET-X invoice billing, so
                    showing NET-60 there is misleading. Mirrors the
                    contracts/page.tsx + form fix for T4/T5. */}
                {summary.data?.fundingSource !== "WALLET" &&
                  summary.data?.fundingSource !== "LICENSE" && (
                  <StatCard
                    title="Payment terms"
                    value={`NET-${summary.data?.paymentTermsDays ?? 60}`}
                  />
                )}
                {summary.data?.fundingSource && (
                  <StatCard
                    title="Funding source"
                    value={FUNDING_SOURCE_LABEL[summary.data.fundingSource]}
                  />
                )}
              </DashboardGrid>
            )}

            {/* #777 §B: INVOICE-funded credit ceiling vs. live outstanding
                (issued+overdue). `creditLimitPaise` null/absent = unlimited;
                we say so rather than fabricating a cap. "Used" reuses the
                outstanding total already aggregated by the billing query. */}
            {summary.data?.fundingSource === "INVOICE" && (
              <p className="text-sm text-zinc-500">
                {summary.data.creditLimitPaise == null ? (
                  <>
                    {formatCurrencyAmount(
                      summary.data.outstanding.amount,
                      "INR",
                    )}{" "}
                    outstanding · no credit limit set (unlimited)
                  </>
                ) : (
                  <>
                    {formatCurrencyAmount(
                      summary.data.outstanding.amount,
                      "INR",
                    )}{" "}
                    of{" "}
                    {formatCurrencyAmount(summary.data.creditLimitPaise, "INR")}{" "}
                    credit limit used
                    {summary.data.outstanding.amount >=
                      summary.data.creditLimitPaise && (
                      <span className="ml-1 font-medium text-amber-600">
                        — limit reached
                      </span>
                    )}
                  </>
                )}
              </p>
            )}

            {/* #779 §B: org can't move money until ACTIVE; surface the reason
                inline so the disabled Pay/Top-up affordances aren't silent. */}
            {moneyMoveBlocked && (
              <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
                <Lock className="mt-0.5 h-4 w-4 shrink-0" />
                <p>{moneyMoveReason}. Paying invoices and wallet top-ups are
                  disabled until then.</p>
              </div>
            )}

        <Card className="mt-6">
          <CardHeader>
            <CardTitle className="text-base">Invoices</CardTitle>
            <CardDescription>
              Manual + auto-generated invoices for this organization.
            </CardDescription>
          </CardHeader>
          <CardContent>
            {invoices.isLoading ? (
              <p className="text-sm text-zinc-500">Loading…</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Number</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Due</TableHead>
                    <TableHead className="w-24"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {invoices.data?.invoices.map((inv) => (
                    <TableRow key={inv.id}>
                      <TableCell className="font-mono text-xs">
                        {inv.invoiceNumber}
                      </TableCell>
                      <TableCell>
                        {formatCurrencyAmount(inv.totalPaise, inv.displayCurrency)}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={
                            inv.status === "PAID"
                              ? "default"
                              : inv.status === "OVERDUE"
                                ? "destructive"
                                : "outline"
                          }
                        >
                          {/* FDE: quantify the lateness so OVERDUE isn't an
                              undated alarm — "OVERDUE · 5 days late". */}
                          {inv.status === "OVERDUE"
                            ? `OVERDUE · ${daysLate(inv.dueDate, inv.createdAt)} days late`
                            : inv.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-xs text-zinc-500">
                        {inv.dueDate
                          ? new Date(inv.dueDate).toLocaleDateString()
                          : "—"}
                      </TableCell>
                      <TableCell>
                        {/* Pay is gated to OWNER on the API; mirror that
                            here so non-owners don't see a button that
                            will 403 on click. MAINTAINERs can view the
                            invoice but only the billing owner pays. */}
                        {(inv.status === "ISSUED" ||
                          inv.status === "OVERDUE") &&
                          isAtLeast("OWNER") && (
                            <Button
                              size="sm"
                              variant={
                                inv.status === "OVERDUE" ? "default" : "outline"
                              }
                              onClick={() => payMutation.mutate(inv.id)}
                              // #779 §B: disable when the org can't move money;
                              // the server rejects anyway, this kills the dead
                              // click. `title` carries the reason on hover.
                              disabled={payMutation.isPending || moneyMoveBlocked}
                              title={moneyMoveBlocked ? moneyMoveReason : undefined}
                            >
                              Pay now
                            </Button>
                          )}
                      </TableCell>
                    </TableRow>
                  ))}
                  {invoices.data && invoices.data.invoices.length === 0 && (
                    <TableRow>
                      <TableCell
                        colSpan={5}
                        className="text-center text-sm text-zinc-500 py-6"
                      >
                        {summary.data?.fundingSource === "LICENSE"
                          ? summary.data.licenseContract?.subscription
                            ? "LICENSE-funded orgs don't generate per-booking invoices. See the Annual License panel above."
                            : "LICENSE-funded orgs don't generate per-booking invoices. The annual license fee covers all usage."
                          : "No invoices yet."}
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
          </TabsContent>

          <TabsContent value="wallet">
            <WalletTab
              orgId={orgId}
              moneyMoveBlocked={moneyMoveBlocked}
              moneyMoveReason={moneyMoveReason}
            />
          </TabsContent>
        </Tabs>
      </DashboardContent>

      {/* Manual invoice composer dialog */}
      <Dialog open={showComposer} onOpenChange={setShowComposer}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Create manual invoice</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Line items</Label>
              {lineItems.map((li, i) => (
                <div key={i} className="flex gap-2 items-end">
                  <Input
                    placeholder="Description"
                    value={li.description}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], description: e.target.value };
                      setLineItems(next);
                    }}
                    className="flex-1"
                  />
                  <Input
                    placeholder="Qty"
                    type="number"
                    min={1}
                    value={li.quantity}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], quantity: parseInt(e.target.value) || 1 };
                      setLineItems(next);
                    }}
                    className="w-16"
                  />
                  <Input
                    placeholder="Price (INR)"
                    type="number"
                    min={0}
                    step="0.01"
                    value={li.unitPrice}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], unitPrice: e.target.value };
                      setLineItems(next);
                    }}
                    className="w-28"
                  />
                  {lineItems.length > 1 && (
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() =>
                        setLineItems(lineItems.filter((_, j) => j !== i))
                      }
                    >
                      <Trash2 className="h-4 w-4 text-red-400" />
                    </Button>
                  )}
                </div>
              ))}
              <Button
                variant="outline"
                size="sm"
                onClick={() =>
                  setLineItems([...lineItems, { description: "", quantity: 1, unitPrice: "" }])
                }
              >
                <Plus className="h-4 w-4 mr-1" /> Add line
              </Button>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="inv-tax">Tax rate (0-1)</Label>
                <Input
                  id="inv-tax"
                  type="number"
                  min="0"
                  max="1"
                  step="0.01"
                  value={taxRate}
                  onChange={(e) => setTaxRate(e.target.value)}
                  placeholder="e.g., 0.18"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="inv-gstin">GSTIN</Label>
                <Input
                  id="inv-gstin"
                  value={gstin}
                  onChange={(e) => setGstin(e.target.value)}
                  placeholder="Optional"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="inv-due">Due date</Label>
              <Input
                id="inv-due"
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
              />
            </div>
            {composerError && (
              <p className="text-sm text-red-600">{composerError}</p>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowComposer(false)}>
              Cancel
            </Button>
            <Button onClick={createInvoice}>Create invoice</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
