"use client";

import { use } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, AlertCircle, Sparkles } from "lucide-react";

import {
  DashboardHeader,
  DashboardContent,
  DashboardGrid,
} from "@/components/dashboard/DashboardShell";
import { StatCard } from "@/components/dashboard/StatCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatCurrencyAmount } from "@/utils/formatting";

interface BillingSummary {
  billingMode: "TAG_ONLY" | "SEAT_PACK" | "INVOICED_MONTHLY";
  monthToDate: { gross: number; paymentCount: number };
  outstanding: { amount: number; invoiceCount: number };
  pendingCharges: { amount: number; paymentCount: number } | null;
  paymentTermsDays: number;
}

interface OrgInvoice {
  id: string;
  invoiceNumber: string;
  amount: number;
  currency: string;
  status: "DRAFT" | "SENT" | "PAID" | "OVERDUE" | "CANCELLED";
  dueDate: string | null;
  paidAt: string | null;
  autoGenerated: boolean;
  createdAt: string;
}

async function fetchBilling(orgId: string): Promise<BillingSummary> {
  const res = await fetch(`/api/organizations/${orgId}/billing`);
  if (!res.ok) throw new Error("Failed to load billing summary");
  return res.json();
}

async function fetchInvoices(
  orgId: string,
): Promise<{ invoices: OrgInvoice[] }> {
  const res = await fetch(`/api/organizations/${orgId}/billing/invoices?limit=50`);
  if (!res.ok) throw new Error("Failed to load invoices");
  return res.json();
}

async function generateInvoice(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing/generate-invoice`,
    { method: "POST" },
  );
  const body = await res.json();
  if (!res.ok) throw new Error(body.error || "Failed to generate invoice");
  return body;
}

async function payInvoice(orgId: string, invoiceId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing/invoices/${invoiceId}/pay`,
    { method: "POST" },
  );
  const body = await res.json();
  if (!res.ok) throw new Error(body.error || "Failed to initiate payment");
  return body;
}

export default function OrgBillingPage({
  params,
}: {
  params: Promise<{ orgId: string }>;
}) {
  const { orgId } = use(params);
  const queryClient = useQueryClient();

  const summary = useQuery({
    queryKey: ["org-billing", orgId],
    queryFn: () => fetchBilling(orgId),
  });
  const invoices = useQuery({
    queryKey: ["org-billing-invoices", orgId],
    queryFn: () => fetchInvoices(orgId),
  });

  const generateMutation = useMutation({
    mutationFn: () => generateInvoice(orgId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["org-billing", orgId] });
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
    },
  });

  const payMutation = useMutation({
    mutationFn: (invoiceId: string) => payInvoice(orgId, invoiceId),
    onSuccess: (result: { pendingPhaseK?: boolean; message?: string }) => {
      if (result.pendingPhaseK) {
        alert(result.message ?? "Gateway integration coming soon.");
      }
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
    },
  });

  return (
    <>
      <DashboardHeader
        title="Billing"
        subtitle="Invoices, charges, and outstanding balance"
        actions={
          summary.data?.billingMode === "INVOICED_MONTHLY" && (
            <Button
              size="sm"
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending}
            >
              <Sparkles className="h-4 w-4 mr-1" /> Generate invoice
            </Button>
          )
        }
      />
      <DashboardContent>
        {summary.isLoading ? (
          <p className="text-sm text-zinc-500">Loading…</p>
        ) : (
          <DashboardGrid columns={4}>
            <StatCard
              title="This month gross"
              value={formatCurrencyAmount(
                summary.data?.monthToDate.gross ?? 0,
                "INR",
              )}
              subtitle={`${summary.data?.monthToDate.paymentCount ?? 0} bookings`}
              icon={CreditCard}
              variant="success"
            />
            <StatCard
              title="Outstanding"
              value={formatCurrencyAmount(
                summary.data?.outstanding.amount ?? 0,
                "INR",
              )}
              subtitle={`${summary.data?.outstanding.invoiceCount ?? 0} invoices`}
              icon={AlertCircle}
              variant={
                (summary.data?.outstanding.invoiceCount ?? 0) > 0
                  ? "warning"
                  : "default"
              }
            />
            {summary.data?.pendingCharges && (
              <StatCard
                title="Pending charges"
                value={formatCurrencyAmount(
                  summary.data.pendingCharges.amount,
                  "INR",
                )}
                subtitle={`${summary.data.pendingCharges.paymentCount} unbilled`}
                icon={CreditCard}
              />
            )}
            <StatCard
              title="Payment terms"
              value={`NET-${summary.data?.paymentTermsDays ?? 30}`}
            />
          </DashboardGrid>
        )}

        <Card className="mt-6">
          <CardHeader>
            <CardTitle className="text-base">Invoices</CardTitle>
            <CardDescription>
              Manual + auto-generated invoices for this organization.
            </CardDescription>
          </CardHeader>
          <CardContent>
            {invoices.isLoading ? (
              <p className="text-sm text-zinc-500">Loading…</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Number</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Due</TableHead>
                    <TableHead className="w-24"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {invoices.data?.invoices.map((inv) => (
                    <TableRow key={inv.id}>
                      <TableCell className="font-mono text-xs">
                        {inv.invoiceNumber}
                      </TableCell>
                      <TableCell>
                        {formatCurrencyAmount(inv.amount, inv.currency)}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={
                            inv.status === "PAID"
                              ? "default"
                              : inv.status === "OVERDUE"
                                ? "destructive"
                                : "outline"
                          }
                        >
                          {inv.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-xs text-zinc-500">
                        {inv.dueDate
                          ? new Date(inv.dueDate).toLocaleDateString()
                          : "—"}
                      </TableCell>
                      <TableCell>
                        {(inv.status === "SENT" ||
                          inv.status === "OVERDUE") && (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => payMutation.mutate(inv.id)}
                            disabled={payMutation.isPending}
                          >
                            Pay
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                  {invoices.data && invoices.data.invoices.length === 0 && (
                    <TableRow>
                      <TableCell
                        colSpan={5}
                        className="text-center text-sm text-zinc-500 py-6"
                      >
                        No invoices yet.
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </DashboardContent>
    </>
  );
}
