"use client";

import { use, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, AlertCircle, Sparkles, Plus, Trash2 } from "lucide-react";
import { useOrgRole, useRequireOrgRole } from "../useOrgRole";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

import {
  DashboardHeader,
  DashboardContent,
  DashboardGrid,
} from "@/components/dashboard/DashboardShell";
import { StatCard } from "@/components/dashboard/StatCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatCurrencyAmount } from "@/utils/formatting";

interface BillingSummary {
  billingMode: "TAG_ONLY" | "SEAT_PACK" | "INVOICED_MONTHLY" | "PREPAID_UNLIMITED" | null;
  monthToDate: { gross: number; paymentCount: number };
  outstanding: { amount: number; invoiceCount: number };
  pendingCharges: { amount: number; paymentCount: number } | null;
  paymentTermsDays: number;
}

interface OrgInvoice {
  id: string;
  invoiceNumber: string;
  amount: number;
  currency: string;
  status: "DRAFT" | "SENT" | "PAID" | "OVERDUE" | "CANCELLED";
  dueDate: string | null;
  paidAt: string | null;
  autoGenerated: boolean;
  createdAt: string;
}

async function fetchBilling(orgId: string): Promise<BillingSummary> {
  const res = await fetch(`/api/organizations/${orgId}/billing`);
  if (!res.ok) throw new Error("Failed to load billing summary");
  return res.json();
}

async function fetchInvoices(
  orgId: string,
): Promise<{ invoices: OrgInvoice[] }> {
  const res = await fetch(`/api/organizations/${orgId}/billing/invoices?limit=50`);
  if (!res.ok) throw new Error("Failed to load invoices");
  return res.json();
}

async function generateInvoice(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing/generate-invoice`,
    { method: "POST" },
  );
  const body = await res.json();
  if (!res.ok) throw new Error(body.error || "Failed to generate invoice");
  return body;
}

async function payInvoice(orgId: string, invoiceId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing/invoices/${invoiceId}/pay`,
    { method: "POST" },
  );
  const body = await res.json();
  if (!res.ok) throw new Error(body.error || "Failed to initiate payment");
  return body;
}

export default function OrgBillingPage({
  params,
}: {
  params: Promise<{ orgId: string }>;
}) {
  const { orgId } = use(params);
  const { isAtLeast } = useOrgRole(orgId);
  const { allowed } = useRequireOrgRole(orgId, "ORG_MANAGER");
  const queryClient = useQueryClient();

  const summary = useQuery({
    queryKey: ["org-billing", orgId],
    queryFn: () => fetchBilling(orgId),
  });
  const invoices = useQuery({
    queryKey: ["org-billing-invoices", orgId],
    queryFn: () => fetchInvoices(orgId),
  });

  const generateMutation = useMutation({
    mutationFn: () => generateInvoice(orgId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["org-billing", orgId] });
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
    },
  });

  const payMutation = useMutation({
    mutationFn: (invoiceId: string) => payInvoice(orgId, invoiceId),
    onSuccess: (result: {
      orderId?: string;
      key?: string;
      amount?: number;
    }) => {
      if (result.orderId && result.key && result.amount && typeof window !== "undefined") {
        const options: RazorpayOptions = {
          key: result.key,
          amount: result.amount,
          currency: "INR",
          name: "Familiarise",
          description: "Invoice Payment",
          order_id: result.orderId,
          handler: () => {
            queryClient.invalidateQueries({
              queryKey: ["org-billing-invoices", orgId],
            });
            queryClient.invalidateQueries({
              queryKey: ["org-billing", orgId],
            });
          },
        };
        const rzp = new window.Razorpay(options);
        rzp.open();
      } else {
        queryClient.invalidateQueries({
          queryKey: ["org-billing-invoices", orgId],
        });
      }
    },
  });

  // Manual invoice composer state
  const [showComposer, setShowComposer] = useState(false);
  const [lineItems, setLineItems] = useState([
    { description: "", quantity: 1, unitPrice: "" },
  ]);
  const [taxRate, setTaxRate] = useState("");
  const [gstin, setGstin] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [composerError, setComposerError] = useState<string | null>(null);

  if (!allowed) return null;

  async function createInvoice() {
    setComposerError(null);
    const items = lineItems
      .filter((li) => li.description.trim())
      .map((li) => ({
        description: li.description.trim(),
        quantity: li.quantity,
        unitPrice: Math.round(parseFloat(li.unitPrice || "0") * 100),
      }));
    if (items.length === 0) {
      setComposerError("Add at least one line item.");
      return;
    }
    const res = await fetch(`/api/organizations/${orgId}/billing/invoices`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        items,
        taxRate: taxRate ? parseFloat(taxRate) : undefined,
        gstin: gstin || undefined,
        dueDate: dueDate || undefined,
      }),
    });
    const body = await res.json();
    if (!res.ok) {
      setComposerError(body.error || "Failed to create invoice");
      return;
    }
    queryClient.invalidateQueries({ queryKey: ["org-billing-invoices", orgId] });
    setShowComposer(false);
    setLineItems([{ description: "", quantity: 1, unitPrice: "" }]);
  }

  return (
    <>
      <DashboardHeader
        title="Billing"
        subtitle="Invoices, charges, and outstanding balance"
        actions={
          <div className="flex gap-2">
            {isAtLeast("ORG_OWNER") && (
              <Button size="sm" variant="outline" onClick={() => setShowComposer(true)}>
                <Plus className="h-4 w-4 mr-1" /> Create invoice
              </Button>
            )}
            {isAtLeast("ORG_OWNER") &&
              summary.data?.billingMode === "INVOICED_MONTHLY" && (
              <Button
                size="sm"
                onClick={() => generateMutation.mutate()}
                disabled={generateMutation.isPending}
              >
                <Sparkles className="h-4 w-4 mr-1" /> Generate invoice
              </Button>
            )}
          </div>
        }
      />
      <DashboardContent>
        {summary.isLoading ? (
          <p className="text-sm text-zinc-500">Loading…</p>
        ) : (
          <DashboardGrid columns={4}>
            <StatCard
              title="This month gross"
              value={formatCurrencyAmount(
                summary.data?.monthToDate.gross ?? 0,
                "INR",
              )}
              subtitle={`${summary.data?.monthToDate.paymentCount ?? 0} bookings`}
              icon={CreditCard}
              variant="success"
            />
            <StatCard
              title="Outstanding"
              value={formatCurrencyAmount(
                summary.data?.outstanding.amount ?? 0,
                "INR",
              )}
              subtitle={`${summary.data?.outstanding.invoiceCount ?? 0} invoices`}
              icon={AlertCircle}
              variant={
                (summary.data?.outstanding.invoiceCount ?? 0) > 0
                  ? "warning"
                  : "default"
              }
            />
            {summary.data?.pendingCharges && (
              <StatCard
                title="Pending charges"
                value={formatCurrencyAmount(
                  summary.data.pendingCharges.amount,
                  "INR",
                )}
                subtitle={`${summary.data.pendingCharges.paymentCount} unbilled`}
                icon={CreditCard}
              />
            )}
            <StatCard
              title="Payment terms"
              value={`NET-${summary.data?.paymentTermsDays ?? 30}`}
            />
            {summary.data?.billingMode && (
              <StatCard
                title="Billing mode"
                value={
                  summary.data.billingMode === "PREPAID_UNLIMITED"
                    ? "Prepaid Unlimited"
                    : summary.data.billingMode === "SEAT_PACK"
                    ? "Seat Pack"
                    : summary.data.billingMode === "INVOICED_MONTHLY"
                    ? "Invoiced Monthly"
                    : "Tag Only"
                }
              />
            )}
          </DashboardGrid>
        )}

        <Card className="mt-6">
          <CardHeader>
            <CardTitle className="text-base">Invoices</CardTitle>
            <CardDescription>
              Manual + auto-generated invoices for this organization.
            </CardDescription>
          </CardHeader>
          <CardContent>
            {invoices.isLoading ? (
              <p className="text-sm text-zinc-500">Loading…</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Number</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Due</TableHead>
                    <TableHead className="w-24"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {invoices.data?.invoices.map((inv) => (
                    <TableRow key={inv.id}>
                      <TableCell className="font-mono text-xs">
                        {inv.invoiceNumber}
                      </TableCell>
                      <TableCell>
                        {formatCurrencyAmount(inv.amount, inv.currency)}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={
                            inv.status === "PAID"
                              ? "default"
                              : inv.status === "OVERDUE"
                                ? "destructive"
                                : "outline"
                          }
                        >
                          {inv.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-xs text-zinc-500">
                        {inv.dueDate
                          ? new Date(inv.dueDate).toLocaleDateString()
                          : "—"}
                      </TableCell>
                      <TableCell>
                        {(inv.status === "SENT" ||
                          inv.status === "OVERDUE") && (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => payMutation.mutate(inv.id)}
                            disabled={payMutation.isPending}
                          >
                            Pay
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                  {invoices.data && invoices.data.invoices.length === 0 && (
                    <TableRow>
                      <TableCell
                        colSpan={5}
                        className="text-center text-sm text-zinc-500 py-6"
                      >
                        No invoices yet.
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </DashboardContent>

      {/* Manual invoice composer dialog */}
      <Dialog open={showComposer} onOpenChange={setShowComposer}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Create manual invoice</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Line items</Label>
              {lineItems.map((li, i) => (
                <div key={i} className="flex gap-2 items-end">
                  <Input
                    placeholder="Description"
                    value={li.description}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], description: e.target.value };
                      setLineItems(next);
                    }}
                    className="flex-1"
                  />
                  <Input
                    placeholder="Qty"
                    type="number"
                    min={1}
                    value={li.quantity}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], quantity: parseInt(e.target.value) || 1 };
                      setLineItems(next);
                    }}
                    className="w-16"
                  />
                  <Input
                    placeholder="Price (INR)"
                    type="number"
                    min={0}
                    step="0.01"
                    value={li.unitPrice}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], unitPrice: e.target.value };
                      setLineItems(next);
                    }}
                    className="w-28"
                  />
                  {lineItems.length > 1 && (
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() =>
                        setLineItems(lineItems.filter((_, j) => j !== i))
                      }
                    >
                      <Trash2 className="h-4 w-4 text-red-400" />
                    </Button>
                  )}
                </div>
              ))}
              <Button
                variant="outline"
                size="sm"
                onClick={() =>
                  setLineItems([...lineItems, { description: "", quantity: 1, unitPrice: "" }])
                }
              >
                <Plus className="h-4 w-4 mr-1" /> Add line
              </Button>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="inv-tax">Tax rate (0-1)</Label>
                <Input
                  id="inv-tax"
                  type="number"
                  min="0"
                  max="1"
                  step="0.01"
                  value={taxRate}
                  onChange={(e) => setTaxRate(e.target.value)}
                  placeholder="e.g., 0.18"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="inv-gstin">GSTIN</Label>
                <Input
                  id="inv-gstin"
                  value={gstin}
                  onChange={(e) => setGstin(e.target.value)}
                  placeholder="Optional"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="inv-due">Due date</Label>
              <Input
                id="inv-due"
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
              />
            </div>
            {composerError && (
              <p className="text-sm text-red-600">{composerError}</p>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowComposer(false)}>
              Cancel
            </Button>
            <Button onClick={createInvoice}>Create invoice</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
