/**
 * #771 / #749 — INVOICE accrual rollup.
 *
 * INVOICE_ACCRUAL PaymentLegs accrue per booking, but nothing rolled them into
 * an OrganizationInvoice (the "Generate invoice" button 404'd and manual create
 * orphaned the legs — so NET-30/60 orgs were never actually billed). This
 * gathers an org's unbilled accruals into one OrganizationInvoice with a line
 * per booking, computes GST, and stamps `Payment.billableToOrgInvoiceId` so the
 * next run can't double-bill.
 *
 * Reused by the cycle-close cron (`jobs/billing/settle-invoice-accruals.ts`)
 * and the "Generate invoice" action. The booking already debited ORG_RECEIVABLE
 * in the double-entry ledger at accrual time; the receivable clears when the
 * org pays the invoice (see `handleOrgPaymentSuccess`). Overage CHARGE_ORG
 * rollup is added once the overage writer lands (#715).
 */
import prisma from "@/lib/prisma";
import { deriveGstBreakdown } from "@/lib/compliance/gst";
import { generateOrgInvoiceNumber } from "./invoice-numbering";
import { transitionOverage } from "./overage-transitions";

export interface RollupResult {
  invoiceId: string | null;
  invoiceNumber: string | null;
  billedPaymentCount: number;
  subtotalPaise: number;
  totalPaise: number;
}

const EMPTY: RollupResult = {
  invoiceId: null,
  invoiceNumber: null,
  billedPaymentCount: 0,
  subtotalPaise: 0,
  totalPaise: 0,
};

/**
 * Roll an org's unbilled INVOICE_ACCRUAL bookings into one OrganizationInvoice.
 * Returns an empty result when there is nothing to bill.
 */
export async function rollupOrgInvoiceAccruals(params: {
  organizationId: string;
  issueImmediately?: boolean;
  billingCycleStart?: Date | null;
  billingCycleEnd?: Date | null;
}): Promise<RollupResult> {
  const { organizationId } = params;

  const org = await prisma.organization.findUnique({
    where: { id: organizationId },
    select: {
      id: true,
      slug: true,
      invoiceNumberPrefix: true,
      billingAccountId: true,
      dataResidencyRegion: true,
      paymentTermsDays: true,
      taxInfo: {
        select: { gstStateCode: true, gstin: true, hsnDefault: true },
      },
    },
  });
  if (!org?.billingAccountId) return EMPTY;

  // Unbilled accrued bookings: org-tagged, succeeded payments carrying an
  // INVOICE_ACCRUAL leg not yet attached to an invoice.
  const accrued = await prisma.payment.findMany({
    where: {
      organizationId,
      billableToOrgInvoiceId: null,
      paymentStatus: "SUCCEEDED",
      legs: {
        some: {
          source: { in: ["INVOICE_ACCRUAL", "OVERAGE_INVOICE_ACCRUAL"] },
        },
      },
    },
    select: {
      id: true,
      // Bill the base accrual AND any CHARGE_ORG overage (#715) on the booking.
      legs: {
        where: {
          source: { in: ["INVOICE_ACCRUAL", "OVERAGE_INVOICE_ACCRUAL"] },
        },
        select: { amountPaise: true },
      },
    },
  });
  if (accrued.length === 0) return EMPTY;

  const lines = accrued.map((p, i) => ({
    position: i,
    paymentId: p.id,
    description: `Sponsored session (booking ${p.id.slice(0, 8)})`,
    quantity: 1,
    unitPricePaise: p.legs.reduce((s, l) => s + l.amountPaise, 0),
  }));
  const subtotal = lines.reduce((s, l) => s + l.unitPricePaise, 0);
  if (subtotal <= 0) return EMPTY;

  const gst = deriveGstBreakdown({
    subtotalPaise: subtotal,
    supplierStateCode: process.env.SUPPLIER_STATE_CODE ?? "KA",
    buyerStateCode: org.taxInfo?.gstStateCode ?? null,
    buyerCountry: org.dataResidencyRegion === "IN" ? "IN" : "US",
    hsnCode: org.taxInfo?.hsnDefault,
  });

  const issuedAt = new Date();
  const issueImmediately = params.issueImmediately ?? true;
  const dueDate = new Date(issuedAt);
  dueDate.setDate(dueDate.getDate() + (org.paymentTermsDays ?? 60));

  return prisma.$transaction(async (tx) => {
    const { invoiceNumber, fiscalYear } = await generateOrgInvoiceNumber(
      tx,
      { id: org.id, slug: org.slug, invoiceNumberPrefix: org.invoiceNumberPrefix },
      issuedAt,
    );

    const invoice = await tx.organizationInvoice.create({
      data: {
        billingAccountId: org.billingAccountId!,
        organizationId,
        invoiceNumber,
        fiscalYear,
        status: issueImmediately ? "ISSUED" : "DRAFT",
        displayCurrency: "INR",
        inrEquivalentPaise: gst.totalPaise,
        subtotalPaise: gst.subtotalPaise,
        igstPaise: gst.igstPaise,
        cgstPaise: gst.cgstPaise,
        sgstPaise: gst.sgstPaise,
        totalPaise: gst.totalPaise,
        taxRate:
          gst.igstPaise + gst.cgstPaise + gst.sgstPaise > 0 ? 0.18 : 0,
        hsnCode: gst.hsnCode,
        placeOfSupply: gst.placeOfSupply,
        reverseCharge: gst.reverseCharge,
        gstin: org.taxInfo?.gstin ?? null,
        irpStatus: "PENDING",
        autoGenerated: true,
        issuedAt: issueImmediately ? issuedAt : null,
        dueDate,
        billingCycleStart: params.billingCycleStart ?? null,
        billingCycleEnd: params.billingCycleEnd ?? null,
        lineItems: {
          create: lines.map((l) => ({
            position: l.position,
            description: l.description,
            quantity: l.quantity,
            unitPricePaise: l.unitPricePaise,
            paymentId: l.paymentId,
            hsnCode: gst.hsnCode,
          })),
        },
      },
    });

    // Stamp the accrued payments. The `billableToOrgInvoiceId: null` guard makes
    // a concurrent run a no-op for already-claimed payments.
    await tx.payment.updateMany({
      where: {
        id: { in: accrued.map((p) => p.id) },
        billableToOrgInvoiceId: null,
      },
      data: { billableToOrgInvoiceId: invoice.id },
    });

    // #771 / #715 — mark CHARGE_ORG overage events for these bookings settled so
    // the next run can't re-bill them. Their marginal is already in the line
    // amounts via the OVERAGE_INVOICE_ACCRUAL legs summed above.
    //
    // #768 #14/#15 — also stamp invoiceLineItemId so each event points at the
    // exact InvoiceLineItem it rolled into (auditability + reversal). updateMany
    // can't set per-row distinct values, so we map paymentId → lineItemId from
    // the line items we just created (one line per payment) and update per event.
    const createdLineItems = await tx.invoiceLineItem.findMany({
      where: { invoiceId: invoice.id, paymentId: { not: null } },
      select: { id: true, paymentId: true },
    });
    const lineItemByPaymentId = new Map(
      createdLineItems.map((li) => [li.paymentId!, li.id]),
    );

    const overageEvents = await tx.overageEvent.findMany({
      where: {
        overageBehavior: "CHARGE_ORG",
        settledAt: null,
        bookingUtilization: { paymentId: { in: accrued.map((p) => p.id) } },
      },
      select: { id: true, bookingUtilization: { select: { paymentId: true } } },
    });

    const settledAt = new Date();
    for (const ev of overageEvents) {
      // #775 — PENDING → ACCRUED: now on an issued invoice. The invoice-paid
      // ledger handler flips ACCRUED → CHARGED on payment.
      await transitionOverage(tx, { id: ev.id }, "ACCRUED", {
        settledAt,
        invoiceLineItemId:
          lineItemByPaymentId.get(ev.bookingUtilization.paymentId) ?? null,
      });
    }

    return {
      invoiceId: invoice.id,
      invoiceNumber,
      billedPaymentCount: accrued.length,
      subtotalPaise: gst.subtotalPaise,
      totalPaise: gst.totalPaise,
    };
  });
}
