"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6tV77gdctIQ
 */
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogTrigger
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/use-toast";
import { TSlotTiming } from "@/lib/datetimetz";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

// Types
type TReview = {
  id: string;
  rating: number;
  reviewDescription: string;
  consultantProfile: TConsultantProfile;
  consulteeProfile: {
    name: string;
  };
  createdAt: string;
  updatedAt: string;
};

type TUserDetails = {
  id: string;
  name: string;
  email: string;
  emailVerified: string;
  image: string;
  phone: string;
  address: string;
  onboardingCompleted: boolean;
  role: string;
  consultantProfileId: string | null;
  consulteeProfileId: string | null;
};

type TConsultantProfile = {
  id: string;
  rating: number;
  specialization: string;
  experience: string;
  location: string;
  onlineStatus: boolean;
  domain: string;
  subDomains: string[];
  userId: string;
  createdAt: string;
  updatedAt: string;
  scheduleType: "WEEKLY" | "CUSTOM";
  slotsOfAvailabiltyWeekly: TWeeklySlot[];
  slotsOfAvailabiltyCustom: TCustomSlot[];
  consultationPlans: TConsultationPlan[];
};

type TConsultationPlan = {
  id: string;
  duration: number;
  price: number;
  consultantProfileId: string;
  createdAt: string;
  updatedAt: string;
}

type TWeeklySlot = {
  id: string;
  dayOfWeekforStartTimeInUTC: string;
  slotStartTimeInUTC: string;
  dayOfWeekforEndTimeInUTC: string;
  slotEndTimeInUTC: string;
};

type TCustomSlot = {
  id: string;
  slotStartTimeInUTC: string;
  slotEndTimeInUTC: string;
};

// API functions
const fetchConsultantDetails = async (id: string): Promise<TConsultantProfile> => {
  const response = await fetch(`/api/user/consultants/${id}`);
  if (!response.ok) throw new Error("Failed to fetch consultant details");
  return response.json();
};

const fetchUserDetails = async (id: string): Promise<{ data: TUserDetails }> => {
  const response = await fetch(`/api/user/${id}`);
  if (!response.ok) throw new Error("Failed to fetch user details");
  return response.json();
};

const fetchSelectedDateSlotTimings = async (consultantId: string, date: Date): Promise<TSlotTiming[]> => {
  const userTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const response = await fetch(
    `/api/slots/availability/${encodeURIComponent(consultantId)}?date=${encodeURIComponent(date.toISOString())}&timeZone=${encodeURIComponent(userTimeZone)}`
  );
  if (!response.ok) throw new Error("Failed to fetch available slots");
  return response.json();
};

const fetchReviews = async (consultantId: string): Promise<TReview[]> => {
  const response = await fetch(`/api/user/reviews?consultantId=${consultantId}`);
  if (!response.ok) throw new Error("Failed to fetch reviews");
  return response.json();
};

const Review = (review: TReview) => (
  <div className="flex items-center space-x-4">
    <Avatar className="w-12 h-12" />
    <div className="flex flex-col flex-1">
      <div className="flex items-center justify-between">
        <div>
          <h4 className="text-lg font-semibold">{review.consulteeProfile.name}</h4>
          <p className="text-sm text-gray-500">{new Date(review.createdAt).toLocaleDateString()}</p>
        </div>
        <div className="flex items-center space-x-1">
          {[...Array(5)].map((_, i) => (
            <StarIcon
              key={`${review.id}-${i}`}
              className={`w-5 h-5 ${i < review.rating ? "text-blue-500" : "text-gray-300"}`}
            />
          ))}
        </div>
      </div>
      <p className="text-gray-600">{review.reviewDescription}</p>
    </div>
  </div>
);

const ConsultantSkeletonLoader = () => {
  const [loadingText, setLoadingText] = useState("Please wait while we are fetching consultant details");

  useEffect(() => {
    const dots = [".", "..", "..."];
    let dotIndex = 0;

    const interval = setInterval(() => {
      setLoadingText(prevText => {
        const baseText = "Please wait while we are fetching consultant details";
        return `${baseText}${dots[dotIndex]}`;
      });
      dotIndex = (dotIndex + 1) % dots.length;
    }, 500);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="flex flex-col justify-center items-center py-40 min-h-screen">
      <div className="text-2xl font-semibold mb-8 text-center animate-pulse">{loadingText}</div>
      <div className="flex justify-center w-full max-w-6xl">
        <div className="flex flex-col w-1/2">
          <Skeleton className="h-8 w-32 mb-2" />
          <Skeleton className="h-10 w-64 mb-4" />
          <Skeleton className="h-6 w-full mb-4" />
          <Skeleton className="h-40 w-full mb-6" />
          <Skeleton className="h-6 w-full mb-2" />
          <Skeleton className="h-24 w-full mb-6" />
          <Skeleton className="h-6 w-full mb-2" />
          <Skeleton className="h-24 w-full" />
        </div>
        <div className="flex flex-col items-center w-1/4 ml-10">
          <Skeleton className="h-64 w-64 rounded-full mb-6" />
          <Skeleton className="h-80 w-full rounded-lg" />
        </div>
      </div>
    </div>
  );
};

// Main component
export default function ExpertProfile({ params }: { readonly params: { consultantId: string } }) {
  const [userDetails, setUserDetails] = useState<TUserDetails | null>(null);
  const [consultantDetails, setConsultantDetails] = useState<TConsultantProfile | null>(null);
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [slotTimings, setSlotTimings] = useState<TSlotTiming[]>([]);
  const [selectedSlot, setSelectedSlot] = useState<TSlotTiming | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [reviews, setReviews] = useState<TReview[]>([]);
  const { toast } = useToast();

  useEffect(() => {
    const fetchConsultantAndUserInfo = async () => {
      setIsLoading(true);
      try {
        const data = await fetchConsultantDetails(params.consultantId);
        setConsultantDetails(data);
        const userData = await fetchUserDetails(data.userId);
        setUserDetails(userData.data);
        const reviewsData = await fetchReviews(params.consultantId);
        setReviews(reviewsData);
      } catch (error: any) {
        console.error("Error fetching consultant details:", error);
        toast({
          title: "Error fetching consultant details",
          description: error.message,
          variant: "destructive",
        });
        setConsultantDetails(null);
        setUserDetails(null);
      } finally {
        setIsLoading(false);
      }
    };

    fetchConsultantAndUserInfo();
  }, [params.consultantId, toast]);

  useEffect(() => {
    if (selectedDate) {
      fetchSelectedDateSlotTimings(params.consultantId, selectedDate)
        .then(setSlotTimings)
        .catch((error) => {
          console.error("Error fetching slots:", error);
          toast({
            title: "Error fetching slots",
            description: error.message,
            variant: "destructive",
          });
        });
    }
  }, [selectedDate, params.consultantId, toast]);

  const handleBooking = async () => {
    if (!selectedSlot) {
      toast({ title: "Please select a time slot", variant: "destructive" });
      return;
    }

    try {
      const response = await fetch("/api/book-consultation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          consultantId: params.consultantId,
          slotId: selectedSlot.slotId,
          date: selectedDate,
        }),
      });

      if (response.ok) {
        toast({ title: "Booking request sent successfully" });
      } else {
        toast({
          title: "Failed to send booking request",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Booking error:", error);
      toast({ title: "An error occurred", variant: "destructive" });
    }
  };

  const renderCalendar = () => {
    const daysInMonth = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0).getDate();
    const firstDayOfMonth = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1).getDay();
    const days = [];

    for (let i = 0; i < firstDayOfMonth; i++) {
      days.push(<div key={`empty-${i}`} className="p-2"></div>);
    }

    for (let i = 1; i <= daysInMonth; i++) {
      const date = new Date(currentDate.getFullYear(), currentDate.getMonth(), i);
      days.push(
        <button
          key={i}
          className={`p-2 rounded-full hover:bg-white hover:bg-opacity-20 
            ${selectedDate?.getDate() === i ? "bg-white text-black" : ""}`}
          onClick={() => setSelectedDate(date)}
        >
          {i}
        </button>
      );
    }

    return days;
  };

  const renderAvailability = () => {
    if (!consultantDetails) return null;

    const daysOfWeek = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

    if (consultantDetails.scheduleType === 'WEEKLY') {
      return (
        <div className="bg-white rounded-lg shadow-lg p-8 border border-gray-200">
          <h3 className="text-2xl font-semibold mb-6 text-center text-gray-800">Weekly Availability</h3>
          <div className="grid grid-cols-7 gap-6 mb-6">
            {daysOfWeek.map((day) => (
              <div key={day} className="text-center text-sm font-semibold text-gray-700">{day}</div>
            ))}
          </div>
          <div className="grid grid-cols-7 gap-6">
            {daysOfWeek.map((day) => (
              <div key={day} className="space-y-3">
                {consultantDetails.slotsOfAvailabiltyWeekly
                  .filter((slot) => slot.dayOfWeekforStartTimeInUTC === day.toUpperCase())
                  .map((slot) => {
                    const startTime = new Date(slot.slotStartTimeInUTC);
                    const endTime = new Date(slot.slotEndTimeInUTC);
                    return (
                      <div 
                        key={slot.id} 
                        className="bg-blue-50 rounded-md p-2 cursor-pointer hover:bg-blue-100 transition-all duration-300 shadow-sm hover:shadow-md flex items-center justify-center"
                      >
                        <div className="text-xs font-medium text-blue-700">
                          {startTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} -
                          {endTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </div>
                      </div>
                    );
                  })}
              </div>
            ))}
          </div>
        </div>
      );
    } else if (consultantDetails.scheduleType === 'CUSTOM') {
      const today = new Date();
      const next7Days = Array.from({ length: 7 }, (_, i) => {
        const date = new Date(today);
        date.setDate(today.getDate() + i);
        return date;
      });

      return (
        <div className="bg-white rounded-lg shadow-lg p-8 border border-gray-200">
          <h3 className="text-2xl font-semibold mb-6 text-center text-gray-800">Custom Availability</h3>
          <div className="grid grid-cols-7 gap-6 mb-6">
            {next7Days.map((date) => (
              <div key={date.toISOString()} className="text-center">
                <div className="text-sm font-semibold text-gray-700">{date.toLocaleDateString(undefined, { weekday: 'short' })}</div>
                <div className="text-xs text-gray-500">{date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</div>
              </div>
            ))}
          </div>
          <div className="grid grid-cols-7 gap-6">
            {next7Days.map((date) => (
              <div key={date.toISOString()} className="space-y-3">
                {consultantDetails.slotsOfAvailabiltyCustom
                  .filter((slot) => {
                    const slotDate = new Date(slot.slotStartTimeInUTC);
                    return slotDate.toDateString() === date.toDateString();
                  })
                  .map((slot) => {
                    const startTime = new Date(slot.slotStartTimeInUTC);
                    const endTime = new Date(slot.slotEndTimeInUTC);
                    return (
                      <div 
                        key={slot.id} 
                        className="bg-green-50 rounded-md p-2 cursor-pointer hover:bg-green-100 transition-all duration-300 shadow-sm hover:shadow-md flex items-center justify-center"
                      >
                        <div className="text-xs font-medium text-green-700">
                          {startTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} -
                          {endTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </div>
                      </div>
                    );
                  })}
              </div>
            ))}
          </div>
        </div>
      );
    }

    return null;
  };

  if (isLoading) {
    return <ConsultantSkeletonLoader />;
  }

  if (!consultantDetails || !userDetails) {
    return (
      <div className="flex flex-col items-center justify-center h-screen">
        <h1 className="text-3xl font-bold mb-4">Oops! Consultant not found</h1>
        <p className="text-lg mb-6">Here are some other consultants you might want to try out</p>
        <Link href="/search">
          <Button variant="night" className="rounded-full">Search Consultants</Button>
        </Link>
      </div>
    );
  }

  return (
    <div key={params.consultantId} className="flex justify-center py-40">
      <div className="flex flex-col w-1/2">
        <div className="flex items-center mb-6 text-lg">
          <div className="flex flex-col">
            <Badge className="mb-1" variant="outline">{consultantDetails.specialization}</Badge>
            <h2 className="text-3xl font-semibold">{userDetails.name}</h2>
            <div className="flex items-center my-2">
              {[...Array(5)].map((_, i) => (
                <StarIcon key={`${i}-${consultantDetails.rating}`} className={`w-5 h-5 ${i < consultantDetails.rating ? "text-blue-500" : "text-gray-300"}`} />
              ))}
              <span className="ml-2 text-base">({consultantDetails.rating})</span>
            </div>
            <p className="text-lg">{consultantDetails.subDomains.join(", ")}</p>
          </div>
        </div>
        <div className="mb-6">
          <h3>About</h3>
          <p className="mt-2 text-gray-500">
            {userDetails.name} is a seasoned {consultantDetails.specialization} with {consultantDetails.experience} of experience in the {consultantDetails.domain} sector.
          </p>
          <h3>Expertise and Education</h3>
          <p className="mt-2 text-gray-500">
            {userDetails.name}'s expertise spans multiple industries, with a particular focus on {consultantDetails.subDomains.join(", ")}.
          </p>
          <h3>Client Testimonials</h3>
          <p className="mt-2 text-gray-500">
            Clients commend {userDetails.name} for their strategic insights and result-oriented approach.
          </p>
        </div>
        {/* UI to display Consultant Availability */}
        <div className="mb-6">
          <h3 className="text-lg font-semibold mb-4">Consultant Availability</h3>
          <p className="text-sm text-gray-500 mb-4">
            {consultantDetails.scheduleType === 'WEEKLY'
              ? "Weekly schedule. Select a time slot to schedule a meeting."
              : "Custom schedule for the next 7 days. Select a time slot to schedule a meeting."}
          </p>
          {renderAvailability()}
        </div>
        <div>
          <h3 className="font-semibold text-lg mb-4">All Reviews ({reviews.length})</h3>
          <div className="space-y-4">
            {reviews.map((review) => (
              <Review key={review.id} {...review} />
            ))}
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center w-1/4 ml-10">
        <Image
          alt="Profile"
          className="rounded-full mb-6"
          height="1350"
          src={userDetails.image || "/placeholder.svg"}
          style={{
            aspectRatio: "1080/1350",
            objectFit: "cover",
          }}
          width="1080"
        />
         <div className="card p-6 bg-white shadow-lg rounded-lg w-full">
          <h3 className="text-lg font-semibold mb-4">Consultation Pricing</h3>
          {consultantDetails.consultationPlans.map((plan) => (
            <div key={plan.id} className="mb-4">
              <p className="text-xl font-bold">
                INR {plan.price.toLocaleString('en-IN')}
              </p>
              <p className="text-sm text-gray-600">
                {plan.duration} {plan.duration === 1 ? 'hour' : 'hours'}
              </p>
            </div>
          ))}
          <Dialog>
            <DialogTrigger asChild>
              <Button variant="night">Book Consultation</Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px] lg:max-w-[700px] bg-black bg-opacity-80 text-white p-0 border-none">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
                <div>
                  <h3 className="text-lg font-semibold mb-4">Select a Date</h3>
                  <div className="calendar-container bg-white bg-opacity-10 p-4 rounded-lg">
                    <div className="flex justify-between items-center mb-4">
                      <button className="text-white" onClick={() => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1))}>
                        &lt;
                      </button>
                      <span>
                        {currentDate.toLocaleString("default", {
                          month: "long",
                          year: "numeric",
                        })}
                      </span>
                      <button className="text-white" onClick={() => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1))}>
                        &gt;
                      </button>
                    </div>
                    <div className="grid grid-cols-7 gap-1 text-center">
                      {["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"].map((day) => (
                        <div key={day} className="text-sm font-medium">
                          {day}
                        </div>
                      ))}
                      {renderCalendar()}
                    </div>
                  </div>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-4">Available Time Slots</h3>
                  <div className="bg-white bg-opacity-10 p-4 rounded-lg">
                    {slotTimings.length > 0 ? (
                      <div className="space-y-2">
                        {slotTimings.map((slot) => (
                          <Button
                            key={slot.slotId}
                            variant={selectedSlot?.slotId === slot.slotId ? "outline" : "night"}
                            onClick={() => setSelectedSlot(slot)}
                            className="w-full justify-center text-sm bg-black bg-opacity-80 hover:bg-opacity-100"
                          >
                            {slot.localStartTime} - {slot.localEndTime}
                          </Button>
                        ))}
                      </div>
                    ) : (
                      <p className="text-center">No available slots. Please select a date to refresh.</p>
                    )}
                  </div>
                </div>
              </div>
              <DialogFooter className="p-4 bg-transparent">
                <Button
                  variant="outline"
                  onClick={() => {
                    /* handle cancel */
                  }}
                  className="text-white border-white"
                >
                  Cancel
                </Button>
                <Button
                  variant="night"
                  onClick={handleBooking}
                  disabled={!selectedDate || !selectedSlot}
                >
                  Book Consultation
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>
    </div>
  );
}

function StarIcon(props: Readonly<React.SVGProps<SVGSVGElement>>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
