import { TAppointment } from "@/types/appointment";
import { IAppointment, ISlotOfAppointment, IUser } from "../../../types";

/**
 * Converts TAppointment to IAppointment for compatibility with legacy functions
 * This is a temporary adapter while we migrate the codebase
 */
export function convertTAppointmentToIAppointment(tAppointment: TAppointment): IAppointment {
  return {
    id: tAppointment.id,
    appointmentType: tAppointment.appointmentType,
    slotsOfAppointment: tAppointment.slotsOfAppointment.map((slot): ISlotOfAppointment => ({
      id: slot.id,
      slotStartTimeInUTC: new Date(slot.slotStartTimeInUTC),
      slotEndTimeInUTC: slot.slotEndTimeInUTC ? new Date(slot.slotEndTimeInUTC) : null,
      isTentative: slot.isTentative,
      user: slot.user.map((u): IUser => ({
        id: u.id,
        name: u.name,
        email: u.email,
        image: u.image,
        phone: u.phone,
        address: u.address,
        password: u.password,
        passwordResetToken: u.passwordResetToken,
        passwordResetExpires: u.passwordResetExpires,
        onlineStatus: u.onlineStatus,
        currentTimezone: u.currentTimezone,
        onboardingCompleted: u.onboardingCompleted,
        role: u.role,
        consultantProfileId: u.consultantProfileId,
        consulteeProfileId: u.consulteeProfileId,
        staffProfileId: u.staffProfileId,
      })),
    })),
    consultation: tAppointment.consultation ? {
      id: tAppointment.consultation.id,
      consultationPlan: {
        id: tAppointment.consultation.consultationPlan.id,
        title: tAppointment.consultation.consultationPlan.title,
        description: tAppointment.consultation.consultationPlan.description,
        durationInHours: tAppointment.consultation.consultationPlan.durationInHours,
        price: tAppointment.consultation.consultationPlan.price || 0,
        language: tAppointment.consultation.consultationPlan.language || "English",
        level: tAppointment.consultation.consultationPlan.level || "Beginner",
        prerequisites: tAppointment.consultation.consultationPlan.prerequisites || null,
        materialProvided: tAppointment.consultation.consultationPlan.materialProvided || null,
        learningOutcomes: tAppointment.consultation.consultationPlan.learningOutcomes || [],
        consultantProfile: tAppointment.consultation.consultationPlan.consultantProfile as any,
      },
      requestStatus: tAppointment.consultation.requestStatus,
      requestedBy: {
        id: tAppointment.consultation.requestedBy.id,
        user: {
          name: tAppointment.consultation.requestedBy.user.name,
          image: tAppointment.consultation.requestedBy.user.image,
        },
      },
    } : undefined,
    subscription: tAppointment.subscription ? {
      id: tAppointment.subscription.id,
      subscriptionPlan: {
        id: tAppointment.subscription.subscriptionPlan.id,
        title: tAppointment.subscription.subscriptionPlan.title,
        description: tAppointment.subscription.subscriptionPlan.description,
        durationInMonths: tAppointment.subscription.subscriptionPlan.durationInMonths,
        price: tAppointment.subscription.subscriptionPlan.price || 0,
        callsPerWeek: tAppointment.subscription.subscriptionPlan.callsPerWeek,
        sessionDurationInHours: tAppointment.subscription.subscriptionPlan.sessionDurationInHours || 1,
        videoMeetings: tAppointment.subscription.subscriptionPlan.videoMeetings || 1,
        emailSupport: tAppointment.subscription.subscriptionPlan.emailSupport || "GENERAL",
        language: tAppointment.subscription.subscriptionPlan.language || "English",
        level: tAppointment.subscription.subscriptionPlan.level || "Beginner",
        prerequisites: tAppointment.subscription.subscriptionPlan.prerequisites || null,
        materialProvided: tAppointment.subscription.subscriptionPlan.materialProvided || null,
        learningOutcomes: tAppointment.subscription.subscriptionPlan.learningOutcomes || [],
        consultantProfile: tAppointment.subscription.subscriptionPlan.consultantProfile as any,
      },
      requestStatus: tAppointment.subscription.requestStatus,
      requestedBy: {
        id: tAppointment.subscription.requestedBy.id,
        user: {
          name: tAppointment.subscription.requestedBy.user.name,
          image: tAppointment.subscription.requestedBy.user.image,
        },
      },
      startDate: typeof tAppointment.subscription.startDate === 'string' ? tAppointment.subscription.startDate : tAppointment.subscription.startDate.toISOString(),
      endDate: typeof tAppointment.subscription.endDate === 'string' ? tAppointment.subscription.endDate : tAppointment.subscription.endDate.toISOString(),
    } : undefined,
    webinar: tAppointment.webinar ? {
      id: tAppointment.webinar.id,
      webinarPlan: {
        id: tAppointment.webinar.webinarPlan.id,
        title: tAppointment.webinar.webinarPlan.title,
        description: tAppointment.webinar.webinarPlan.description,
        price: tAppointment.webinar.webinarPlan.price || 0,
        priceCurrency: tAppointment.webinar.webinarPlan.priceCurrency || "INR",
        certificateProvided: tAppointment.webinar.webinarPlan.certificateProvided || false,
        durationInHours: tAppointment.webinar.webinarPlan.durationInHours,
        maxParticipants: tAppointment.webinar.webinarPlan.maxParticipants || 100,
        language: tAppointment.webinar.webinarPlan.language || "English",
        level: tAppointment.webinar.webinarPlan.level || "Beginner",
        prerequisites: tAppointment.webinar.webinarPlan.prerequisites || null,
        materialProvided: tAppointment.webinar.webinarPlan.materialProvided || null,
        learningOutcomes: tAppointment.webinar.webinarPlan.learningOutcomes || [],
        consultantProfile: tAppointment.webinar.webinarPlan.consultantProfile as any,
      },
      status: tAppointment.webinar.status,
    } : undefined,
    class: tAppointment.class ? {
      id: tAppointment.class.id,
      classPlan: {
        id: tAppointment.class.classPlan.id,
        title: tAppointment.class.classPlan.title,
        description: tAppointment.class.classPlan.description,
        price: tAppointment.class.classPlan.price || 0,
        priceCurrency: tAppointment.class.classPlan.priceCurrency || "INR",
        certificateProvided: tAppointment.class.classPlan.certificateProvided || false,
        durationInMonths: tAppointment.class.classPlan.durationInMonths,
        callsPerWeek: tAppointment.class.classPlan.callsPerWeek || 1,
        videoMeetings: tAppointment.class.classPlan.videoMeetings || 1,
        emailSupport: tAppointment.class.classPlan.emailSupport || "GENERAL",
        maxParticipants: tAppointment.class.classPlan.maxParticipants || 1,
        language: tAppointment.class.classPlan.language || "English",
        level: tAppointment.class.classPlan.level || "Beginner",
        prerequisites: tAppointment.class.classPlan.prerequisites || null,
        materialProvided: tAppointment.class.classPlan.materialProvided || null,
        learningOutcomes: tAppointment.class.classPlan.learningOutcomes || [],
        consultantProfile: tAppointment.class.classPlan.consultantProfile as any,
      },
      status: tAppointment.class.status,
    } : undefined,
  };
}