/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yU6zQT3gE3B
 */
"use client"; // Mark as a Client Component

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import {
  CookiePreference,
  NotificationPreference,
  StaffProfile,
  User,
} from "@prisma/client"; // Import types
import Link from "next/link";
import { ChangeEvent, use, useEffect, useState } from "react";

// Define a type for the combined staff data
type StaffData = User & {
  staffProfile: StaffProfile | null;
  notificationPreferences: NotificationPreference | null;
  cookiePreferences: CookiePreference | null;
};

type PageProps = {
  params: Promise<{ staffId: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
};

export default function StaffSettingsPage({ params }: Readonly<PageProps>) {
  const resolvedParams = use(params);
  const { staffId } = resolvedParams;
  const [staffData, setStaffData] = useState<StaffData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false); // To disable buttons during save

  // Fetch data on component mount
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await fetch(`/api/user/staff/${staffId}`);
        if (!response.ok) {
          throw new Error(`Failed to fetch staff data: ${response.statusText}`);
        }
        const data: StaffData = await response.json();
        setStaffData(data);
      } catch (err: any) {
        setError(err.message || "An unknown error occurred");
        console.error("Fetch error:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [staffId]);

  // Handle input changes
  const handleInputChange = (
    e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    const { name, value } = e.target;
    setStaffData((prev) => {
      if (!prev) return null;
      // Handle nested profile fields if necessary (not needed for these inputs)
      return { ...prev, [name]: value };
    });
  };

  const handleSelectChange = (value: string, name: string) => {
    setStaffData((prev) => {
      if (!prev) return null;
      return { ...prev, [name]: value };
    });
  };

  const handleProfileInputChange = (
    e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    const { name, value } = e.target;
    setStaffData((prev) => {
      if (!prev || !prev.staffProfile) return prev;
      return {
        ...prev,
        staffProfile: {
          ...prev.staffProfile,
          [name]: value,
        },
      };
    });
  };

  const handleNotificationChange = (
    checked: boolean,
    name: keyof NotificationPreference,
  ) => {
    setStaffData((prev) => {
      if (!prev) return prev;
      const currentPrefs = prev.notificationPreferences ?? { userId: prev.id }; // Create stub if null
      return {
        ...prev,
        notificationPreferences: {
          ...currentPrefs,
          [name]: checked,
        } as NotificationPreference, // Assert type
      };
    });
  };

  const handleCookieChange = (
    checked: boolean,
    name: keyof CookiePreference,
  ) => {
    setStaffData((prev) => {
      if (!prev) return prev;
      const currentPrefs = prev.cookiePreferences ?? {
        userId: prev.id,
        essential: true,
      }; // Create stub if null
      return {
        ...prev,
        cookiePreferences: {
          ...currentPrefs,
          [name]: checked,
        } as CookiePreference, // Assert type
      };
    });
  };

  // Generic save handler - sends only changed data for a specific section
  const handleSave = async (
    section: "personal" | "role" | "account" | "preferences",
  ) => {
    if (!staffData) return;
    setIsSaving(true);
    setError(null);

    let payload: Partial<StaffData> = {};

    // Construct payload based on section
    switch (section) {
      case "personal":
        payload = {
          name: staffData.name,
          email: staffData.email,
          phone: staffData.phone,
          address: staffData.address,
          image: staffData.image,
        };
        break;
      case "role":
        payload = {
          staffProfile: {
            department: staffData.staffProfile?.department,
            position: staffData.staffProfile?.position,
            // TODO: Handle responsibilities/permissions update if editable
          },
        } as any; // Type assertion needed for partial nested update
        break;
      case "account":
        payload = {
          currentTimezone: staffData.currentTimezone,
          // Add other account fields if they become editable
        };
        break;
      case "preferences":
        payload = {
          notificationPreferences: staffData.notificationPreferences
            ? {
                allNotifications:
                  staffData.notificationPreferences.allNotifications,
                mentions: staffData.notificationPreferences.mentions,
                directMessages:
                  staffData.notificationPreferences.directMessages,
                updates: staffData.notificationPreferences.updates,
              }
            : undefined,
          cookiePreferences: staffData.cookiePreferences
            ? {
                analytics: staffData.cookiePreferences.analytics,
                marketing: staffData.cookiePreferences.marketing,
              }
            : undefined,
        } as any; // Type assertion needed
        break;
    }

    try {
      const response = await fetch(`/api/user/staff/${staffId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(
          errorData.message || `Failed to save ${section} settings`,
        );
      }

      const updatedData: StaffData = await response.json();
      setStaffData(updatedData); // Update state with response data
      alert(
        `${section.charAt(0).toUpperCase() + section.slice(1)} settings saved successfully!`,
      ); // Simple feedback
    } catch (err: any) {
      setError(
        err.message || `An error occurred while saving ${section} settings`,
      );
      console.error("Save error:", err);
      alert(`Error saving ${section} settings: ${err.message}`); // Simple feedback
    } finally {
      setIsSaving(false);
    }
  };

  // Render loading/error states
  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-screen">
        Loading...
      </div>
    );
  }
  if (error) {
    return (
      <div className="flex justify-center items-center min-h-screen text-red-500">
        Error: {error}
      </div>
    );
  }
  if (!staffData) {
    return (
      <div className="flex justify-center items-center min-h-screen">
        Staff member not found.
      </div>
    );
  }

  // Main component render
  return (
    <div className="grid min-h-screen w-full lg:grid-cols-[280px_1fr]">
      {/* Simplified Sidebar */}
      <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
        <div className="flex h-full max-h-screen flex-col gap-2">
          <div className="flex h-[60px] items-center border-b px-6">
            <Link
              className="flex items-center gap-2 font-semibold"
              href="/dashboard"
            >
              <BuildingIcon className="h-6 w-6" />
              <span className="">ConsultX</span>
            </Link>
            <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
              <BellIcon className="h-4 w-4" />
              <span className="sr-only">Toggle notifications</span>
            </Button>
          </div>
          <div className="flex-1 overflow-auto py-2">
            <nav className="grid items-start px-4 text-sm font-medium">
              <Link
                className="flex items-center gap-3 rounded-lg bg-gray-100 px-3 py-2 text-gray-900 transition-all hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-50"
                href={`/dashboard/staff/${staffId}/settings`} // Link to current page
              >
                <SettingsIcon className="h-4 w-4" />
                Settings
              </Link>
            </nav>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        {/* Header */}
        <header className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
          <Link className="lg:hidden" href="#">
            <BuildingIcon className="h-6 w-6" />
            <span className="sr-only">Home</span>
          </Link>
          <div className="w-full flex-1">
            <form>
              <div className="relative">
                <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
                <Input
                  className="w-full bg-white shadow-none appearance-none pl-8 md:w-2/3 lg:w-1/3 dark:bg-gray-950"
                  placeholder="Search..."
                  type="search"
                />
              </div>
            </form>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Avatar className="h-9 w-9">
                <AvatarImage alt="Admin Avatar" src="/placeholder-user.jpg" />
                <AvatarFallback>AD</AvatarFallback>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        {/* Main Content Area */}
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="flex items-center gap-4">
            <Avatar className="h-16 w-16">
              <AvatarImage
                alt={staffData.name ?? "Staff"}
                src={staffData.image ?? "/placeholder.svg"}
              />
              <AvatarFallback>
                {staffData.name
                  ?.split(" ")
                  .map((n) => n[0])
                  .join("") ?? "ST"}
              </AvatarFallback>
            </Avatar>
            <div>
              <h1 className="font-semibold text-lg md:text-2xl">
                Staff Settings
              </h1>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Manage profile and account settings for{" "}
                {staffData.name ?? `Staff ID: ${staffId}`}.
              </p>
            </div>
          </div>

          {/* No longer using a single form, handle saves per card */}
          <div className="grid gap-6">
            {/* Personal Information Card */}
            <Card>
              <CardHeader>
                <CardTitle>Personal Information</CardTitle>
                <CardDescription>
                  Update the staff member's personal details.
                </CardDescription>
              </CardHeader>
              <CardContent className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input
                    id="name"
                    name="name"
                    placeholder="Full Name"
                    value={staffData.name ?? ""}
                    onChange={handleInputChange}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    name="email"
                    type="email"
                    placeholder="Email Address"
                    value={staffData.email ?? ""}
                    onChange={handleInputChange}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="phone">Phone</Label>
                  <Input
                    id="phone"
                    name="phone"
                    type="tel"
                    placeholder="Phone Number"
                    value={staffData.phone ?? ""}
                    onChange={handleInputChange}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="address">Address</Label>
                  <Textarea
                    id="address"
                    name="address"
                    placeholder="Street Address"
                    value={staffData.address ?? ""}
                    onChange={handleInputChange}
                    className="min-h-[80px]"
                  />
                </div>
                <div className="space-y-2 md:col-span-2">
                  <Label htmlFor="image">Profile Picture URL</Label>
                  <Input
                    id="image"
                    name="image"
                    placeholder="https://example.com/avatar.png"
                    value={staffData.image ?? ""}
                    onChange={handleInputChange}
                  />
                </div>
              </CardContent>
              <CardFooter className="border-t px-6 py-4">
                <Button
                  onClick={() => handleSave("personal")}
                  disabled={isSaving}
                >
                  {isSaving ? "Saving..." : "Save Personal Info"}
                </Button>
              </CardFooter>
            </Card>

            {/* Staff Role Card */}
            <Card>
              <CardHeader>
                <CardTitle>Staff Role</CardTitle>
                <CardDescription>
                  Manage the staff member's role and responsibilities.
                </CardDescription>
              </CardHeader>
              <CardContent className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="department">Department</Label>
                  <Input
                    id="department"
                    name="department"
                    placeholder="e.g., Engineering, Marketing"
                    value={staffData.staffProfile?.department ?? ""}
                    onChange={handleProfileInputChange}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="position">Position</Label>
                  <Input
                    id="position"
                    name="position"
                    placeholder="e.g., Software Engineer, Manager"
                    value={staffData.staffProfile?.position ?? ""}
                    onChange={handleProfileInputChange}
                  />
                </div>
                {/* Displaying Responsibilities/Permissions as read-only */}
                <div className="space-y-2 md:col-span-2">
                  <Label>Responsibilities</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {/* TODO: Improve display/editing for JSON */}
                    {JSON.stringify(staffData.staffProfile?.responsibilities) ??
                      "Not specified"}
                  </p>
                </div>
                <div className="space-y-2 md:col-span-2">
                  <Label>Permissions</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {JSON.stringify(staffData.staffProfile?.permissions) ??
                      "Not specified"}
                  </p>
                </div>
              </CardContent>
              <CardFooter className="border-t px-6 py-4">
                <Button onClick={() => handleSave("role")} disabled={isSaving}>
                  {isSaving ? "Saving..." : "Save Role Info"}
                </Button>
              </CardFooter>
            </Card>

            {/* Account Settings Card */}
            <Card>
              <CardHeader>
                <CardTitle>Account Settings</CardTitle>
                <CardDescription>
                  Manage account-related settings.
                </CardDescription>
              </CardHeader>
              <CardContent className="grid gap-4">
                <div className="space-y-2">
                  <Label htmlFor="timezone">Timezone</Label>
                  <Select
                    name="currentTimezone"
                    value={staffData.currentTimezone ?? ""}
                    onValueChange={(value) =>
                      handleSelectChange(value, "currentTimezone")
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select timezone" />
                    </SelectTrigger>
                    <SelectContent>
                      {/* Populate with actual timezones - Placeholder */}
                      <SelectItem value="America/New_York">
                        Eastern Time (US & Canada)
                      </SelectItem>
                      <SelectItem value="Europe/London">London</SelectItem>
                      <SelectItem value="Asia/Kolkata">
                        India Standard Time
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </CardContent>
              <CardFooter className="border-t px-6 py-4">
                <Button
                  onClick={() => handleSave("account")}
                  disabled={isSaving}
                >
                  {isSaving ? "Saving..." : "Save Account Settings"}
                </Button>
              </CardFooter>
            </Card>

            {/* Preferences Card */}
            <Card>
              <CardHeader>
                <CardTitle>Preferences</CardTitle>
                <CardDescription>
                  Manage notification and cookie preferences.
                </CardDescription>
              </CardHeader>
              <CardContent className="grid gap-6">
                {/* Notification Preferences */}
                <div className="space-y-4">
                  <h3 className="font-medium">Notifications</h3>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="allNotifications"
                      className="flex flex-col space-y-1 cursor-pointer"
                    >
                      <span>All Notifications</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Enable or disable all notifications globally.
                      </span>
                    </Label>
                    <Switch
                      id="allNotifications"
                      name="allNotifications"
                      checked={
                        staffData.notificationPreferences?.allNotifications ??
                        false
                      }
                      onCheckedChange={(checked) =>
                        handleNotificationChange(checked, "allNotifications")
                      }
                    />
                  </div>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="mentions"
                      className="flex flex-col space-y-1 cursor-pointer"
                    >
                      <span>Mentions</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Receive notifications for @mentions.
                      </span>
                    </Label>
                    <Switch
                      id="mentions"
                      name="mentions"
                      checked={
                        staffData.notificationPreferences?.mentions ?? false
                      }
                      onCheckedChange={(checked) =>
                        handleNotificationChange(checked, "mentions")
                      }
                    />
                  </div>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="directMessages"
                      className="flex flex-col space-y-1 cursor-pointer"
                    >
                      <span>Direct Messages</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Receive notifications for direct messages.
                      </span>
                    </Label>
                    <Switch
                      id="directMessages"
                      name="directMessages"
                      checked={
                        staffData.notificationPreferences?.directMessages ??
                        false
                      }
                      onCheckedChange={(checked) =>
                        handleNotificationChange(checked, "directMessages")
                      }
                    />
                  </div>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="updates"
                      className="flex flex-col space-y-1 cursor-pointer"
                    >
                      <span>Platform Updates</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Receive notifications about platform updates and news.
                      </span>
                    </Label>
                    <Switch
                      id="updates"
                      name="updates"
                      checked={
                        staffData.notificationPreferences?.updates ?? false
                      }
                      onCheckedChange={(checked) =>
                        handleNotificationChange(checked, "updates")
                      }
                    />
                  </div>
                </div>
                {/* Cookie Preferences */}
                <div className="space-y-4">
                  <h3 className="font-medium">Cookie Preferences</h3>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="essentialCookies"
                      className="flex flex-col space-y-1"
                    >
                      <span>Essential Cookies</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Required for basic site functionality. Cannot be
                        disabled.
                      </span>
                    </Label>
                    <Switch
                      id="essentialCookies"
                      name="essential"
                      checked={staffData.cookiePreferences?.essential ?? true}
                      disabled
                    />
                  </div>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="analyticsCookies"
                      className="flex flex-col space-y-1 cursor-pointer"
                    >
                      <span>Analytics Cookies</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Allow us to collect anonymous usage data.
                      </span>
                    </Label>
                    <Switch
                      id="analyticsCookies"
                      name="analytics"
                      checked={staffData.cookiePreferences?.analytics ?? false}
                      onCheckedChange={(checked) =>
                        handleCookieChange(checked, "analytics")
                      }
                    />
                  </div>
                  <div className="flex items-center justify-between space-x-2">
                    <Label
                      htmlFor="marketingCookies"
                      className="flex flex-col space-y-1 cursor-pointer"
                    >
                      <span>Marketing Cookies</span>
                      <span className="font-normal leading-snug text-muted-foreground">
                        Used for tracking and advertising purposes.
                      </span>
                    </Label>
                    <Switch
                      id="marketingCookies"
                      name="marketing"
                      checked={staffData.cookiePreferences?.marketing ?? false}
                      onCheckedChange={(checked) =>
                        handleCookieChange(checked, "marketing")
                      }
                    />
                  </div>
                </div>
              </CardContent>
              <CardFooter className="border-t px-6 py-4">
                <Button
                  onClick={() => handleSave("preferences")}
                  disabled={isSaving}
                >
                  {isSaving ? "Saving..." : "Save Preferences"}
                </Button>
              </CardFooter>
            </Card>
          </div>
        </main>
      </div>
    </div>
  );
}

// --- Icon Components ---

function BuildingIcon(props: Readonly<React.SVGProps<SVGSVGElement>>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <path d="M8 6h.01" />
      <path d="M16 6h.01" />
      <path d="M12 6h.01" />
      <path d="M12 10h.01" />
      <path d="M12 14h.01" />
      <path d="M16 10h.01" />
      <path d="M16 14h.01" />
      <path d="M8 10h.01" />
      <path d="M8 14h.01" />
    </svg>
  );
}

function BellIcon(props: Readonly<React.SVGProps<SVGSVGElement>>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  );
}

function SearchIcon(props: Readonly<React.SVGProps<SVGSVGElement>>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function SettingsIcon(props: Readonly<React.SVGProps<SVGSVGElement>>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 .54 1.85l-.01.45a2 2 0 0 1-1 1.74l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 .54 1.85l-.01.45a2 2 0 0 1-1 1.74l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 .54 1.85v.19a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.1a2 2 0 0 1-.54-1.85l.01-.45a2 2 0 0 1 1-1.74l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.1a2 2 0 0 1-.54-1.85l.01-.45a2 2 0 0 1 1-1.74l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.1a2 2 0 0 1-.54-1.85v-.19a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}
