/**
 * Org invoices — GET (list) / POST (manual create).
 *
 * GET  — ORG_MANAGER+
 * POST — ORG_OWNER (manual ad-hoc invoice for special charges).
 *        Auto-generated invoices come from /billing/generate-invoice and the
 *        monthly Inngest cron in Phase K.
 *
 * PDF rendering is deferred to Issue #438 — `pdfUrl` stays null until then.
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { requireOrgAccess } from "@/lib/auth-helpers";
import { OrgInvoiceStatus, Prisma } from "@prisma/client";

const lineItemSchema = z.object({
  description: z.string().min(1).max(200),
  quantity: z.number().int().positive(),
  unitPrice: z.number().int().nonnegative(), // in paise
});

// Indian GSTIN: 15-char format — 2-digit state code + PAN (10 chars) + entity number + Z + check digit.
const GSTIN_REGEX = /^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/;

const createInvoiceSchema = z.object({
  items: z.array(lineItemSchema).min(1),
  currency: z.string().length(3).default("INR"),
  taxRate: z.number().min(0).max(1).optional(),
  hsnCode: z.string().optional(),
  gstin: z
    .string()
    .regex(GSTIN_REGEX, "Invalid GSTIN format (expected 15-char format, e.g. 27AABCU9603R1ZX)")
    .optional(),
  dueDate: z.string().datetime().optional(),
  notes: z.string().max(1000).optional(),
});

function generateInvoiceNumber(orgSlug: string): string {
  const yyyymm = new Date().toISOString().slice(0, 7).replace("-", "");
  const random = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `INV-${orgSlug.slice(0, 8).toUpperCase()}-${yyyymm}-${random}`;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ orgId: string }> },
) {
  try {
    const { orgId } = await params;
    const access = await requireOrgAccess(orgId, "ORG_MANAGER");
    if (access.error) return access.error;

    const url = new URL(req.url);
    const status = url.searchParams.get("status") as OrgInvoiceStatus | null;
    const limit = Math.min(parseInt(url.searchParams.get("limit") ?? "20"), 100);
    const offset = Math.max(parseInt(url.searchParams.get("offset") ?? "0"), 0);

    const where = {
      organizationProfileId: access.org.id,
      ...(status && { status }),
    };

    const [invoices, total] = await Promise.all([
      prisma.organizationInvoice.findMany({
        where,
        orderBy: { createdAt: "desc" },
        take: limit,
        skip: offset,
      }),
      prisma.organizationInvoice.count({ where }),
    ]);

    return NextResponse.json({ invoices, total, limit, offset });
  } catch (error) {
    console.error(
      "[API /organizations/[orgId]/billing/invoices GET] error:",
      error,
    );
    return NextResponse.json(
      { error: "Failed to fetch invoices" },
      { status: 500 },
    );
  }
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ orgId: string }> },
) {
  try {
    const { orgId } = await params;
    const access = await requireOrgAccess(orgId, "ORG_OWNER");
    if (access.error) return access.error;

    const body = await req.json();
    const parsed = createInvoiceSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid request body", details: parsed.error.flatten() },
        { status: 400 },
      );
    }

    const { items, currency, taxRate, hsnCode, gstin, dueDate } = parsed.data;
    const subtotal = items.reduce(
      (sum, item) => sum + item.quantity * item.unitPrice,
      0,
    );
    const taxAmount = taxRate ? Math.round(subtotal * taxRate) : 0;
    const amount = subtotal + taxAmount;

    const organization = await prisma.organization.findUnique({
      where: { id: orgId },
      select: { slug: true },
    });

    const invoice = await prisma.organizationInvoice.create({
      data: {
        organizationProfileId: access.org.id,
        invoiceNumber: generateInvoiceNumber(organization?.slug ?? "ORG"),
        amount,
        currency,
        status: "DRAFT",
        items: items as Prisma.InputJsonValue,
        taxAmount: taxRate ? taxAmount : null,
        taxRate: taxRate ?? null,
        hsnCode: hsnCode ?? "999293",
        gstin: gstin ?? null,
        dueDate: dueDate ? new Date(dueDate) : null,
        autoGenerated: false,
      },
    });

    return NextResponse.json({ invoice }, { status: 201 });
  } catch (error) {
    console.error(
      "[API /organizations/[orgId]/billing/invoices POST] error:",
      error,
    );
    return NextResponse.json(
      { error: "Failed to create invoice" },
      { status: 500 },
    );
  }
}
