/**
 * Manual trigger for the INVOICED_MONTHLY invoice generator.
 *
 * POST — ORG_OWNER. Aggregates unbilled Payment rows for the calling org and
 * rolls them into a single OrganizationInvoice. Useful for testing and for
 * orgs that want to close out a billing cycle ahead of the monthly cron.
 *
 * Phase K will move the core aggregation logic into
 * `lib/payments/operations/org-invoicing.ts` and call it both from this route
 * and the monthly Inngest cron. For now we inline a minimum-viable version so
 * the dashboard can render real data.
 */

import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireOrgAccess } from "@/lib/auth-helpers";

function generateInvoiceNumber(orgSlug: string): string {
  const yyyymm = new Date().toISOString().slice(0, 7).replace("-", "");
  const random = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `INV-${orgSlug.slice(0, 8).toUpperCase()}-${yyyymm}-${random}`;
}

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ orgId: string }> },
) {
  try {
    const { orgId } = await params;
    const access = await requireOrgAccess(orgId, "ORG_OWNER");
    if (access.error) return access.error;

    if (access.org.billingMode !== "INVOICED_MONTHLY") {
      return NextResponse.json(
        {
          error: `This operation is only valid for INVOICED_MONTHLY orgs (current mode: ${access.org.billingMode}).`,
        },
        { status: 400 },
      );
    }

    // Aggregate every payment tagged to this org that is not yet billed.
    // Joining `appointment` so the line items can carry the booking type.
    const unbilled = await prisma.payment.findMany({
      where: {
        organizationProfileId: access.org.id,
        billableToOrgInvoiceId: null,
      },
      select: {
        id: true,
        amount: true,
        createdAt: true,
        appointment: { select: { appointmentType: true } },
      },
      orderBy: { createdAt: "asc" },
    });

    if (unbilled.length === 0) {
      return NextResponse.json(
        { error: "No unbilled payments to invoice for this period." },
        { status: 400 },
      );
    }

    const subtotal = unbilled.reduce((sum, p) => sum + (p.amount ?? 0), 0);
    const items = unbilled.map((p) => ({
      paymentId: p.id,
      description: `Booking (${p.appointment?.appointmentType ?? "UNKNOWN"})`,
      quantity: 1,
      unitPrice: p.amount ?? 0,
    }));

    const periodStart = unbilled[0].createdAt;
    const periodEnd = unbilled[unbilled.length - 1].createdAt;

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + access.org.paymentTermsDays);

    const organization = await prisma.organization.findUnique({
      where: { id: orgId },
      select: { slug: true },
    });

    const invoice = await prisma.$transaction(async (tx) => {
      const created = await tx.organizationInvoice.create({
        data: {
          organizationProfileId: access.org.id,
          invoiceNumber: generateInvoiceNumber(organization?.slug ?? "ORG"),
          amount: subtotal,
          currency: "INR",
          status: "SENT",
          items: items as unknown as object,
          billingCycleStart: periodStart,
          billingCycleEnd: periodEnd,
          autoGenerated: false,
          dueDate,
        },
      });

      await tx.payment.updateMany({
        where: { id: { in: unbilled.map((p) => p.id) } },
        data: { billableToOrgInvoiceId: created.id },
      });

      return created;
    });

    return NextResponse.json({ invoice }, { status: 201 });
  } catch (error) {
    console.error(
      "[API /organizations/[orgId]/billing/generate-invoice POST] error:",
      error,
    );
    return NextResponse.json(
      { error: "Failed to generate invoice" },
      { status: 500 },
    );
  }
}
