/**
 * Cron: generate BillingSubscription-driven invoices — REAL (Issue #681).
 *
 * Schedule: daily at 01:00 IST.
 * Scope: every `BillingSubscription` with `nextInvoiceDate <= now`.
 *
 * For each due subscription:
 *   1. Compute the invoice amount (flatFeePaise for FLAT_FEE, or
 *      activeSeatCount × ratePerSeatPaise for PER_SEAT).
 *   2. Create an OrganizationInvoice with GST breakdown (stubbed via
 *      lib/compliance/gst.ts).
 *   3. Advance nextInvoiceDate by the subscription cycle.
 *   4. Emit a SettlementLedgerEntry (kind=INVOICE_ISSUED).
 *
 * IRP upload is handled by the separate `irp-uploader.ts` cron.
 */

import prisma from "@/lib/prisma";
import { deriveGstBreakdown } from "@/lib/compliance/gst";
import { Currency, OrgInvoiceStatus } from "@prisma/client";

export async function runGenerateSubscriptionInvoices(): Promise<{
  generated: number;
}> {
  const now = new Date();

  const dueSubs = await prisma.billingSubscription.findMany({
    where: { nextInvoiceDate: { lte: now } },
    include: {
      contract: { include: { organization: { select: { id: true, gstStateCode: true, gstin: true } } } },
      billingAccount: true,
    },
  });

  let generated = 0;
  for (const sub of dueSubs) {
    const subtotal =
      sub.model === "FLAT_FEE"
        ? (sub.flatFeePaise ?? 0)
        : (sub.ratePerSeatPaise ?? 0) * sub.activeSeatCount;
    if (subtotal <= 0) {
      console.warn(`[cron] Skipping subscription ${sub.id} with non-positive subtotal`);
      continue;
    }

    const gst = deriveGstBreakdown({
      subtotalPaise: subtotal,
      supplierStateCode: "KA",
      buyerStateCode: sub.contract.organization.gstStateCode,
      buyerCountry: "IN",
    });

    const dueDate = new Date(now);
    dueDate.setDate(dueDate.getDate() + sub.contract.paymentTermsDays);

    // Include the subscription id suffix so an org with two subs due the
    // same day doesn't collide on the unique invoiceNumber constraint.
    const invoiceNumber = `AUTO-${sub.contract.organization.id.slice(0, 6)}-${now
      .toISOString()
      .slice(0, 10)
      .replace(/-/g, "")}-${sub.id.slice(0, 8)}`;

    const invoice = await prisma.organizationInvoice.create({
      data: {
        billingAccountId: sub.billingAccountId,
        organizationId: sub.contract.organization.id,
        invoiceNumber,
        status: OrgInvoiceStatus.ISSUED,
        displayCurrency: Currency.INR,
        inrEquivalentPaise: gst.totalPaise,
        subtotalPaise: gst.subtotalPaise,
        igstPaise: gst.igstPaise,
        cgstPaise: gst.cgstPaise,
        sgstPaise: gst.sgstPaise,
        totalPaise: gst.totalPaise,
        hsnCode: gst.hsnCode,
        placeOfSupply: gst.placeOfSupply,
        reverseCharge: gst.reverseCharge,
        gstin: sub.contract.organization.gstin,
        items: [
          {
            description:
              sub.model === "FLAT_FEE"
                ? "Enterprise license flat fee"
                : `Per-seat license × ${sub.activeSeatCount} seats`,
            quantity: sub.model === "PER_SEAT" ? sub.activeSeatCount : 1,
            unitPrice:
              sub.model === "FLAT_FEE"
                ? sub.flatFeePaise ?? 0
                : sub.ratePerSeatPaise ?? 0,
          },
        ],
        issuedAt: now,
        dueDate,
        billingCycleStart: sub.currentCycleStart,
        billingCycleEnd: sub.currentCycleEnd,
        autoGenerated: true,
      },
    });

    // Advance cycle
    const nextStart = sub.currentCycleEnd;
    const nextEnd = new Date(nextStart);
    if (sub.cycle === "MONTHLY") nextEnd.setMonth(nextEnd.getMonth() + 1);
    else if (sub.cycle === "QUARTERLY") nextEnd.setMonth(nextEnd.getMonth() + 3);
    else nextEnd.setFullYear(nextEnd.getFullYear() + 1);

    await prisma.billingSubscription.update({
      where: { id: sub.id },
      data: {
        currentCycleStart: nextStart,
        currentCycleEnd: nextEnd,
        nextInvoiceDate: nextEnd,
      },
    });

    await prisma.settlementLedgerEntry.create({
      data: {
        organizationId: sub.contract.organization.id,
        invoiceId: invoice.id,
        kind: "INVOICE_ISSUED",
        amountPaise: invoice.totalPaise,
        currency: Currency.INR,
      },
    });

    generated++;
  }

  console.log(`[cron] generate-subscription-invoices: ${generated} invoices created`);
  return { generated };
}
