/**
 * Harness bits shared by the SSO e2e suites. Deliberately tiny — see the note
 * at the bottom for why there is no general-purpose IdP here.
 *
 * ## Everything in this file is loopback-only
 *
 * The OIDC server binds `127.0.0.1` on an **ephemeral port** (`listen(0)`), so
 * two suites — or two Jest workers, or a developer's laptop with something
 * already on 8080 — cannot collide, and no test can reach the public internet.
 * It is also `unref()`d: a suite that dies before `close()` leaks a handle that
 * can no longer hold the event loop open, so a failed run fails instead of
 * hanging CI until the job timeout.
 *
 * ## Why `node-forge` is here and not `crypto`
 *
 * `node:crypto` can generate an RSA keypair and can *parse* an X.509 cert
 * (`X509Certificate`), but it cannot **mint** one. Both halves are needed: SAML
 * signature verification extracts the public key from a real certificate, so a
 * bare `BEGIN PUBLIC KEY` will not do, and `validateSamlCert` in
 * `lib/sso/provider-schemas.ts` requires a genuine `-----BEGIN CERTIFICATE-----`
 * block anyway. `node-forge` is already in the tree as a transitive dependency
 * of `samlify` — the very library `@better-auth/sso` uses for SAML — so this
 * adds no new SAML machinery, only a test-only cert generator.
 *
 * The keypair itself is generated by `node:crypto` (native, ~ms) and only the
 * certificate *wrapping* is done in pure-JS forge, which is the slow part we
 * avoid.
 */

import { generateKeyPairSync } from "node:crypto";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import forge from "node-forge";

/** An IdP signing identity: the private key signs, the certificate is verified against. */
export interface MockIdpCredentials {
  /** PKCS#8 PEM. Handed to `samlify` as the IdP's `privateKey`. */
  readonly privateKey: string;
  /** Self-signed X.509 PEM. Handed to `samlify` as `signingCert` and stored as the provider's `cert`. */
  readonly cert: string;
}

/**
 * Mint a self-signed IdP certificate whose public key matches the returned
 * private key, so a response signed with `privateKey` verifies against `cert`.
 *
 * Validity is one day: long enough for a test run, short enough that a cert
 * generated by a developer months ago and pasted into a fixture cannot quietly
 * outlive its usefulness. Nothing checks the dates here — `validateSamlCert`
 * only parses, and samlify's timestamp validation applies to the *assertion*,
 * not the signing cert.
 */
export function mintSelfSignedIdpCredentials(): MockIdpCredentials {
  const { privateKey, publicKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  const keys = forge.pki.privateKeyFromPem(privateKey);
  const cert = forge.pki.createCertificate();
  cert.publicKey = forge.pki.publicKeyFromPem(publicKey);
  cert.serialNumber = "01";
  cert.validity.notBefore = new Date(Date.now() - 60_000);
  cert.validity.notAfter = new Date(Date.now() + 86_400_000);

  const subject = [{ name: "commonName", value: "sso-e2e-mock-idp" }];
  cert.setSubject(subject);
  cert.setIssuer(subject);
  cert.sign(keys, forge.md.sha256.create());

  return { privateKey, cert: forge.pki.certificateToPem(cert) };
}

/** The subset of a discovery document these suites care about. */
export interface MockOidcDiscovery {
  readonly issuer: string;
  readonly discoveryEndpoint: string;
  readonly close: () => Promise<void>;
}

/**
 * Serve a real OIDC discovery document over loopback HTTP.
 *
 * `endpoints` is a function rather than a fixed object so the advertised URLs
 * are built from the port the OS actually handed out — a hardcoded
 * `https://idp.example.com` would make the test assert against a string that
 * nothing serves, which is the failure mode this whole exercise exists to
 * eliminate.
 */
export async function startOidcDiscoveryServer(
  buildEndpoints: (issuer: string) => {
    authorization_endpoint: string;
    token_endpoint: string;
    jwks_uri: string;
    userinfo_endpoint: string;
  },
): Promise<MockOidcDiscovery> {
  let issuer = "";

  const server = createServer((req, res) => {
    const path = (req.url ?? "").split("?")[0];
    if (path !== "/.well-known/openid-configuration") {
      res.writeHead(404, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: "not_found" }));
      return;
    }
    res.writeHead(200, { "content-type": "application/json" });
    res.end(
      JSON.stringify({
        issuer,
        ...buildEndpoints(issuer),
        response_types_supported: ["code"],
        subject_types_supported: ["public"],
        id_token_signing_alg_values_supported: ["RS256"],
        scopes_supported: ["openid", "email", "profile", "offline_access"],
        token_endpoint_auth_methods_supported: [
          "client_secret_basic",
          "client_secret_post",
        ],
      }),
    );
  });

  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      server.removeListener("error", reject);
      resolve();
    });
  });

  // A leaked listener must not be able to keep the process alive.
  server.unref();

  const { port } = server.address() as AddressInfo;
  issuer = `http://127.0.0.1:${port}`;

  return {
    issuer,
    discoveryEndpoint: `${issuer}/.well-known/openid-configuration`,
    close: () =>
      new Promise<void>((resolve, reject) => {
        server.close((err) => (err ? reject(err) : resolve()));
      }),
  };
}

/**
 * ## Why there is no `createMockSamlIdP` in here
 *
 * The obvious thing to reach for is a mock SAML IdP HTTP server, since
 * `@better-auth/sso`'s own test suite has one. That suite is **not in the
 * published package** (`node_modules/@better-auth/sso` ships `dist/` only — its
 * `.test.*` files are absent, so there is no reference implementation to copy),
 * and building one would mean hand-rolling XML templating that `samlify` already
 * does correctly.
 *
 * So the SAML "IdP" in `saml.e2e.test.ts` is a `samlify.IdentityProvider` used
 * in-process: the same library, the same class, the same signing and
 * verification code paths, minus the socket. That is a strictly better trade —
 * real crypto, real protocol, and **no port to leak**, which is the failure the
 * brief called out. Only OIDC needs a socket, and only because discovery is
 * specified as an HTTP fetch.
 */
