/**
 * Harness bits shared by the SSO e2e suites. Deliberately tiny — see the note
 * at the bottom for why the SAML IdP is in-process rather than a server.
 *
 * ## Everything in this file is loopback-only
 *
 * The OIDC server binds `127.0.0.1` on an **ephemeral port** (`listen(0)`), so
 * two suites — or two Jest workers, or a developer's laptop with something
 * already on 8080 — cannot collide, and no test can reach the public internet.
 * It is also `unref()`d: a suite that dies before `close()` leaks a handle that
 * can no longer hold the event loop open, so a failed run fails instead of
 * hanging CI until the job timeout.
 *
 * The SAML half binds nothing at all. It is a `samlify.IdentityProvider` driven
 * in-process, so there is no port, no socket and nothing to leak.
 *
 * ## Why `node-forge` is here and not `crypto`
 *
 * `node:crypto` can generate an RSA keypair and can *parse* an X.509 cert
 * (`X509Certificate`), but it cannot **mint** one. Both halves are needed: SAML
 * signature verification extracts the public key from a real certificate, so a
 * bare `BEGIN PUBLIC KEY` will not do, and `validateSamlCert` in
 * `lib/sso/provider-schemas.ts` requires a genuine `-----BEGIN CERTIFICATE-----`
 * block anyway. `node-forge` is already in the tree as a transitive dependency
 * of `samlify` — the very library `@better-auth/sso` uses for SAML — so this
 * adds no new SAML machinery, only a test-only cert generator. See
 * `__tests__/fixtures/node-forge.d.ts` for the same argument about its types.
 *
 * The keypair itself is generated by `node:crypto` (native, ~ms) and only the
 * certificate *wrapping* is done in pure-JS forge, which is the slow part we
 * avoid.
 *
 * `fast-xml-parser` is a transitive dependency for the same reason, and with
 * the same caveat: it is not a declared devDependency here (adding one would
 * desynchronise `package-lock.json` and break `npm ci`), it is present because
 * `@better-auth/sso` depends on it directly (`package.json`), and the harness
 * uses the *same* parser the plugin does so a document the harness accepts is a
 * document production accepts.
 */

import { generateKeyPairSync, randomUUID } from "node:crypto";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import forge from "node-forge";
import { XMLValidator } from "fast-xml-parser";
import * as saml from "samlify";

/** An IdP signing identity: the private key signs, the certificate is verified against. */
export interface MockIdpCredentials {
  /** PKCS#8 PEM. Handed to `samlify` as the IdP's `privateKey`. */
  readonly privateKey: string;
  /** Self-signed X.509 PEM. Handed to `samlify` as `signingCert` and stored as the provider's `cert`. */
  readonly cert: string;
}

/**
 * Mint a self-signed IdP certificate whose public key matches the returned
 * private key, so a response signed with `privateKey` verifies against `cert`.
 *
 * Validity is one day: long enough for a test run, short enough that a cert
 * generated by a developer months ago and pasted into a fixture cannot quietly
 * outlive its usefulness. Nothing checks the dates here — `validateSamlCert`
 * only parses, and samlify's timestamp validation applies to the *assertion*,
 * not the signing cert.
 */
export function mintSelfSignedIdpCredentials(): MockIdpCredentials {
  const { privateKey, publicKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  const keys = forge.pki.privateKeyFromPem(privateKey);
  const cert = forge.pki.createCertificate();
  cert.publicKey = forge.pki.publicKeyFromPem(publicKey);
  cert.serialNumber = "01";
  cert.validity.notBefore = new Date(Date.now() - 60_000);
  cert.validity.notAfter = new Date(Date.now() + 86_400_000);

  const subject = [{ name: "commonName", value: "sso-e2e-mock-idp" }];
  cert.setSubject(subject);
  cert.setIssuer(subject);
  cert.sign(keys, forge.md.sha256.create());

  return { privateKey, cert: forge.pki.certificateToPem(cert) };
}

/* ------------------------------------------------------------------------ *
 * SAML: an in-process IdP that can actually mint a signed assertion.
 * ------------------------------------------------------------------------ */

type MockSamlIdp = ReturnType<typeof saml.IdentityProvider>;
type MockSamlSp = ReturnType<typeof saml.ServiceProvider>;

/** `urn:oasis:names:tc:SAML:2.0:attrname-format:basic` — what the mock IdP declares. */
const ATTRIBUTE_NAME_FORMAT =
  "urn:oasis:names:tc:SAML:2.0:attrname-format:basic";
const EMAIL_NAME_ID_FORMAT =
  "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress";
const STATUS_SUCCESS = "urn:oasis:names:tc:SAML:2.0:status:Success";

let schemaValidatorInstalled = false;

/**
 * Register samlify's XML schema validator — **the same one the plugin installs**.
 *
 * ## Why this has to exist at all
 *
 * `samlify` does not validate XML on its own. `libsaml.isValidXml` reads a
 * validator off a module-level context and, if there is none, rejects with
 * "Your application is potentially vulnerable because no validation function
 * found" (`build/src/libsaml.js:682-685`). `@better-auth/sso` registers one at
 * `dist/index.mjs:2980`, so in production every parse is guarded. A harness
 * that imports `samlify` on its own does **not** get that for free, and the
 * failure it produces is actively misleading:
 *
 *   - `postFlow` awaits `isValidXml` outside any `try` (`flow.js:198`), so the
 *     rejection surfaces as the long "no validation function" string.
 *   - `redirectFlow` wraps the *same* call in a `try` and flattens **any**
 *     rejection to the literal string `'ERR_INVALID_XML'` (`flow.js:105-112`).
 *
 * So without this call the very first parse of the suite — `idp.parseLoginRequest`
 * over the AuthnRequest — dies with `ERR_INVALID_XML` no matter how well-formed
 * the document is, and the error names the *assertion* while the assertion has
 * not been built yet. That misdirection is why the failure was attributed to a
 * malformed response in the first place.
 *
 * Copying the plugin's validator rather than inventing one is deliberate: a
 * document this harness accepts is then, by construction, a document the ACS in
 * production would also accept. The rejection is a bare `throw` of a string
 * because that is verbatim what `dist/index.mjs:2982` does, and matching it
 * keeps the harness's failure signature identical to production's.
 *
 * Idempotent, because it writes module-global state inside `samlify` and
 * re-registering an equivalent validator is noise, not an error.
 */
export function installSamlSchemaValidator(): void {
  if (schemaValidatorInstalled) return;
  saml.setSchemaValidator({
    async validate(xml: string) {
      if (XMLValidator.validate(xml, { allowBooleanAttributes: true }) === true) {
        return "SUCCESS_VALIDATE_XML";
      }
      // A bare string throw, exactly as `dist/index.mjs:2982` does it.
      throw "ERR_INVALID_XML";
    },
  });
  schemaValidatorInstalled = true;
}

/** The subject the mock IdP asserts, keyed to the attribute `valueTag`s below. */
export interface MockSamlSubject {
  readonly email: string;
  readonly emailAddress: string;
  readonly givenName: string;
  readonly surname: string;
  readonly displayName: string;
}

/**
 * Build a `samlify` IdP that can sign a real assertion.
 *
 * ## Why `loginResponseTemplate` is not optional here
 *
 * `IdentityProvider` only *pre-renders* the template in its constructor, and
 * that pre-rendering is what turns the `attributes` array into a concrete
 * `AttributeStatement` full of `{attrXxx}` placeholders
 * (`build/src/entity-idp.js:103-127`). Two consequences, and both are silent:
 *
 *   1. Without a `loginResponseTemplate`, `base64LoginResponse` falls through
 *      to `defaultLoginResponseTemplate` with `AttributeStatement: ''`
 *      (`binding-post.js:181-210`) — a response with **no** `AttributeStatement`
 *      at all. It is still well-formed XML, so nothing errors; `extract.attributes`
 *      is simply empty, and the plugin's identity mapping
 *      (`attributes[mapping.email || "email"] || extract.nameID`) silently
 *      degrades to the NameID.
 *   2. The template branch is only taken when `customTagReplacement` is *also*
 *      passed (`binding-post.js:202-205`). Supplying a template and then
 *      omitting the callback produces the same attribute-less response, with no
 *      warning. That is why `createMockSamlTemplateCallback` exists rather than
 *      a bare tag map: the callback is the only thing that fills the
 *      placeholders.
 *
 * The `context` is samlify's own stock response template. Hand-copying it would
 * mean hand-maintaining a schema in a test file, and a typo there is an
 * `ERR_INVALID_XML` that reads as a plugin bug. The single `{AttributeStatement}`
 * placeholder is the only part that has to differ, and the constructor handles
 * that.
 */
export function createMockSamlIdP(options: {
  entityID: string;
  singleSignOnService: Array<{ Binding: string; Location: string }>;
  signingCert: string;
  privateKey: string;
}): MockSamlIdp {
  return saml.IdentityProvider({
    entityID: options.entityID,
    singleSignOnService: options.singleSignOnService,
    signingCert: options.signingCert,
    privateKey: options.privateKey,
    // `IdpMetadata` never parses `NameIDFormat` into its metadata
    // (`metadata-idp.js:133-146` defines no key for it), so `getNameIDFormat()`
    // is `undefined` and this array is the only source of the NameID format the
    // emitted `<saml:NameID Format="…">` will carry.
    nameIDFormat: [EMAIL_NAME_ID_FORMAT],
    wantAuthnRequestsSigned: false,
    isAssertionEncrypted: false,
    loginResponseTemplate: {
      context: saml.SamlLib.defaultLoginResponseTemplate.context,
      attributes: [
        {
          name: "email",
          valueTag: "emailAddress",
          nameFormat: ATTRIBUTE_NAME_FORMAT,
          valueXsiType: "xs:string",
        },
        {
          name: "givenName",
          valueTag: "givenName",
          nameFormat: ATTRIBUTE_NAME_FORMAT,
          valueXsiType: "xs:string",
        },
        {
          name: "surname",
          valueTag: "surname",
          nameFormat: ATTRIBUTE_NAME_FORMAT,
          valueXsiType: "xs:string",
        },
        {
          name: "displayName",
          valueTag: "displayName",
          nameFormat: ATTRIBUTE_NAME_FORMAT,
          valueXsiType: "xs:string",
        },
      ],
    },
  });
}

/**
 * The SP's HTTP-POST ACS, or a loud failure.
 *
 * ## Why the binding argument is the word, not the URN
 *
 * `getAssertionConsumerService` looks the binding up as
 * `namespace.binding[binding]` (`metadata-sp.js:198-217`) and that map is keyed
 * `{redirect, post, simpleSign, artifact}` → URN (`urn.js:50-54`). Handing it the
 * URN therefore looks up `namespace.binding["urn:…:HTTP-POST"]`, finds
 * `undefined`, matches no entry, and returns **`undefined`** — no throw, no
 * warning. A caller that does not check gets a response whose `Destination`,
 * `SubjectRecipient` and `Recipient` all read `"undefined"`, which is invalid on
 * the wire and, once signed, is exactly the kind of thing that surfaces as an
 * opaque parse failure rather than as a location bug.
 *
 * Hence the guard. This is the single most load-bearing value in the whole ACS
 * direction, and it is worth failing loudly on rather than silently dropping.
 */
function acsUrlOf(sp: MockSamlSp): string {
  const location = sp.entityMeta.getAssertionConsumerService(
    saml.Constants.wording.binding.post,
  );
  if (typeof location !== "string" || location === "") {
    throw new Error(
      `mock IdP: the SP publishes no HTTP-POST ACS (got ${JSON.stringify(location)})`,
    );
  }
  return location;
}

/** Just enough of `FlowResult` to recover the AuthnRequest ID samlify parsed. */
export interface MockSamlRequestInfo {
  extract?: { request?: { id?: string } };
}

/**
 * The `customTagReplacement` callback `createLoginResponse` needs.
 *
 * It receives the pre-rendered template — stock context with the
 * `AttributeStatement` already built from `createMockSamlIdP`'s `attributes` —
 * and returns it with every `{…}` placeholder filled. The tag map is the same
 * one samlify's own default path builds (`binding-post.js:181-201`), so this
 * callback is a *superset* of the stock behaviour rather than a different
 * dialect: the only thing the harness adds is the populated
 * `AttributeStatement`, the `AuthnStatement`, and a real `InResponseTo`.
 *
 * `InResponseTo` is the field the plugin's AuthnRequest-correlation block reads
 * (`dist/index.mjs:1650`), so it is filled here and asserted on the extract.
 * BetterAuth's own mock passes `{}` as `requestInfo` and a template with no
 * `{InResponseTo}` at all, which is fine for checking that an SP can be built
 * and not fine for a round trip that claims correlation.
 *
 * `Destination`, `SubjectRecipient` and `Audience` all come from the **SP's**
 * metadata — never from a literal in this file — so a drifting ACS changes the
 * emitted assertion instead of quietly diverging from it.
 */
export function createMockSamlTemplateCallback(
  idp: MockSamlIdp,
  sp: MockSamlSp,
  subject: MockSamlSubject,
  requestInfo?: MockSamlRequestInfo,
): (template: string) => { id: string; context: string } {
  const mintId = () => idp.entitySetting.generateID?.() ?? `_${randomUUID()}`;

  return (template: string) => {
    const now = new Date();
    const fiveMinutesLater = new Date(now.getTime() + 5 * 60 * 1000);
    const acsUrl = acsUrlOf(sp);
    const spEntityId = sp.entityMeta.getEntityID();
    const idpEntityId = idp.entityMeta.getEntityID();

    const id = mintId();
    // `saml:SamlLib.replaceTagsByValue` is samlify's own escaper: it XML-escapes
    // values interpolated into attributes and leaves element content alone. Using
    // it rather than `String.replace` is what keeps a subject name containing
    // `&` or `"` from producing a document the validator rejects.
    const context = saml.SamlLib.replaceTagsByValue(template, {
      ID: id,
      AssertionID: mintId(),
      Destination: acsUrl,
      SubjectRecipient: acsUrl,
      AssertionConsumerServiceURL: acsUrl,
      Audience: spEntityId,
      EntityID: spEntityId,
      Issuer: idpEntityId,
      IssueInstant: now.toISOString(),
      StatusCode: STATUS_SUCCESS,
      ConditionsNotBefore: now.toISOString(),
      ConditionsNotOnOrAfter: fiveMinutesLater.toISOString(),
      SubjectConfirmationDataNotOnOrAfter: fiveMinutesLater.toISOString(),
      NameIDFormat: idp.entitySetting.nameIDFormat?.[0] ?? EMAIL_NAME_ID_FORMAT,
      NameID: subject.email,
      InResponseTo: requestInfo?.extract?.request?.id ?? "",
      // No `SessionNotOnOrAfter`, so the `verifyTime` branch in `postFlow`
      // (`flow.js:262-267`) is skipped — a session lifetime is SLO's concern and
      // asserting on it here would only add a clock dependency.
      AuthnStatement: [
        '<saml:AuthnStatement AuthnInstant="',
        now.toISOString(),
        '"/>',
      ].join(""),
      // Filled by the `AttributeStatement` the IdP constructor pre-rendered
      // from the `attributes` array. `attributeStatementBuilder` derives each
      // placeholder as `{attr` + camelCase(`valueTag`) + `}`
      // (`libsaml.js:261`), which is why the keys below are `attrEmailAddress`,
      // `attrGivenName` and so on rather than the raw attribute names.
      attrEmailAddress: subject.emailAddress,
      attrGivenName: subject.givenName,
      attrSurname: subject.surname,
      attrDisplayName: subject.displayName,
    });

    return { id, context };
  };
}

/**
 * The SP's HTTP-POST ACS — the one endpoint an assertion in this harness may be
 * delivered to, and the value `createMockSamlTemplateCallback` fills into
 * `Destination`, `SubjectRecipient` and `Recipient`.
 *
 * Exported so a test can assert the SP publishes exactly the URL the mock IdP
 * targets, rather than restating the lookup and risking a second, subtly
 * different, way of asking the same question.
 */
export { acsUrlOf as mockSamlAcsUrl };

/** The subset of a discovery document these suites care about. */
export interface MockOidcDiscovery {
  readonly issuer: string;
  readonly discoveryEndpoint: string;
  readonly close: () => Promise<void>;
}

/**
 * Serve a real OIDC discovery document over loopback HTTP.
 *
 * `endpoints` is a function rather than a fixed object so the advertised URLs
 * are built from the port the OS actually handed out — a hardcoded
 * `https://idp.example.com` would make the test assert against a string that
 * nothing serves, which is the failure mode this whole exercise exists to
 * eliminate.
 */
export async function startOidcDiscoveryServer(
  buildEndpoints: (issuer: string) => {
    authorization_endpoint: string;
    token_endpoint: string;
    jwks_uri: string;
    userinfo_endpoint: string;
  },
): Promise<MockOidcDiscovery> {
  let issuer = "";

  const server = createServer((req, res) => {
    const path = (req.url ?? "").split("?")[0];
    if (path !== "/.well-known/openid-configuration") {
      res.writeHead(404, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: "not_found" }));
      return;
    }
    res.writeHead(200, { "content-type": "application/json" });
    res.end(
      JSON.stringify({
        issuer,
        ...buildEndpoints(issuer),
        response_types_supported: ["code"],
        subject_types_supported: ["public"],
        id_token_signing_alg_values_supported: ["RS256"],
        scopes_supported: ["openid", "email", "profile", "offline_access"],
        token_endpoint_auth_methods_supported: [
          "client_secret_basic",
          "client_secret_post",
        ],
      }),
    );
  });

  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      server.removeListener("error", reject);
      resolve();
    });
  });

  // A leaked listener must not be able to keep the process alive.
  server.unref();

  const { port } = server.address() as AddressInfo;
  issuer = `http://127.0.0.1:${port}`;

  return {
    issuer,
    discoveryEndpoint: `${issuer}/.well-known/openid-configuration`,
    close: () =>
      new Promise<void>((resolve, reject) => {
        server.close((err) => (err ? reject(err) : resolve()));
      }),
  };
}

/**
 * ## Why the SAML "IdP" here is not an HTTP server
 *
 * The obvious thing to reach for is a mock SAML IdP HTTP server, since
 * `@better-auth/sso`'s own test suite has one. That suite is **not in the
 * published package** (`node_modules/@better-auth/sso` ships `dist/` only — its
 * `.test.*` files are absent, so there is no reference implementation to copy),
 * and building one would mean hand-rolling XML templating that `samlify` already
 * does correctly.
 *
 * So the SAML "IdP" in `saml.e2e.test.ts` is a `samlify.IdentityProvider` used
 * in-process: the same library, the same class, the same signing and
 * verification code paths, minus the socket. That is a strictly better trade —
 * real crypto, real protocol, and **no port to leak**, which is the failure the
 * brief called out. Only OIDC needs a socket, and only because discovery is
 * specified as an HTTP fetch.
 *
 * What a socket would *not* have bought, and what `installSamlSchemaValidator`
 * plus `createMockSamlIdP` now supply instead: a validator on samlify's global
 * context, a response template with a real `AttributeStatement`, and the tag
 * callback that fills it. All three are per-process configuration rather than
 * per-connection state, so an in-process IdP is the right home for them.
 */
