/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qs75yL6tAVe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { JSX, SVGProps } from "react"
import { CheckIcon } from "lucide-react"

export default function CheckoutConsultation() {
  return (
    <div className="grid min-h-screen w-full overflow-hidden lg:grid-cols-[60%_40%]">
      <div className="flex flex-col gap-8 border-r bg-muted/40 p-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Avatar className="w-12 h-12 border">
              <AvatarImage src="/placeholder-user.jpg" alt="Consultant" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <div className="font-semibold">John Doe</div>
              <div className="text-sm text-muted-foreground">Consultant</div>
            </div>
          </div>
          <div className="text-right">
            <div className="font-semibold">Consultation</div>
            <div className="text-sm text-muted-foreground">April 15, 2023 at 2:00 PM</div>
          </div>
        </div>
        <Separator className="bg-gray-300" />
        <div className="grid gap-2">
          <div className="font-semibold">Consultant Details</div>
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Specialization</div>
              <div>Software Engineering</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Experience</div>
              <div>5 years</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Location</div>
              <div>San Francisco, CA</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Description</div>
              <div className="text-right">
                John is an experienced software engineer with a passion for building scalable and efficient
                applications.
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Tags</div>
              <div className="flex gap-2">
                <Badge variant="outline">JavaScript</Badge>
                <Badge variant="outline">React</Badge>
                <Badge variant="outline">Node.js</Badge>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Domain</div>
              <div>Technology</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-muted-foreground">Sub-Domains</div>
              <div className="flex gap-2">
                <Badge variant="outline">Web Development</Badge>
                <Badge variant="outline">Mobile Development</Badge>
                <Badge variant="outline">DevOps</Badge>
              </div>
            </div>
          </div>
        </div>
        <Separator className="bg-gray-300" />
        <div className="grid gap-4">
          <div className="font-semibold">Discount Codes</div>
          <div className="flex items-center gap-2">
            <Input type="text" placeholder="Enter discount code" className="flex-1" />
            <Button variant="outline">Apply</Button>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <div>
                <div className="font-medium">SUMMERSALE10</div>
                <div className="text-sm text-muted-foreground">Get 10% off your purchase during the summer sale</div>
              </div>
              <div className="flex items-center gap-2">
                <div className="text-muted-foreground">10% off</div>
                <Button variant="outline" size="sm">
                  Apply
                </Button>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <div className="font-medium">NEWCUSTOMER15</div>
                <div className="text-sm text-muted-foreground">New customers get 15% off their first order</div>
              </div>
              <div className="flex items-center gap-2">
                <div className="text-muted-foreground">15% off</div>
                <Button variant="outline" size="sm">
                  Apply
                </Button>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <div className="font-medium">FREESHIP</div>
                <div className="text-sm text-muted-foreground">Enjoy free shipping on your order</div>
              </div>
              <div className="flex items-center gap-2">
                <div className="text-muted-foreground">Free Shipping</div>
                <Button variant="outline" size="sm">
                  Apply
                </Button>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <div className="font-medium">HOLIDAY20</div>
                <div className="text-sm text-muted-foreground">Get 20% off during the holiday season</div>
              </div>
              <div className="flex items-center gap-2">
                <div className="text-muted-foreground">20% off</div>
                <Button variant="outline" size="sm">
                  Apply
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-8 p-6">
        <Card>
          <CardHeader>
            <CardTitle>Pricing</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <div>1 hour</div>
                <div>$100</div>
              </div>
              <div className="flex items-center justify-between">
                <div>2 hours</div>
                <div>$200</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <span className="font-semibold">3 hours</span>
                  <CheckIcon className="w-4 h-4 mr-2" />
                </div>
                <div className="font-semibold">$300</div>
              </div>
            </div>
            <Separator className="bg-gray-300" />
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <div>Subtotal</div>
                <div>$300</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Tax (10%)</div>
                <div>$30</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Discount (10%)</div>
                <div>-$30</div>
              </div>
              <Separator className="bg-gray-300" />
              <div className="flex items-center justify-between font-semibold">
                <div>Net Amount</div>
                <div>$300</div>
              </div>
            </div>
          </CardContent>
        </Card>
        <div className="grid gap-4">
          <div className="grid gap-2">
            <div className="font-semibold">Payment</div>
            <div className="text-muted-foreground">Select your preferred payment method</div>
          </div>
          <Card>
            <CardHeader>
              <CardTitle>Stripe</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <CreditCardIcon className="w-8 h-8" />
                  <div>
                    <div className="font-semibold">Credit/Debit Card</div>
                    <div className="text-sm text-muted-foreground">Securely pay with your card</div>
                  </div>
                </div>
                <Button variant="outline">Pay with Stripe</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Razorpay</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <CreditCardIcon className="w-8 h-8" />
                  <div>
                    <div className="font-semibold">Credit/Debit Card</div>
                    <div className="text-sm text-muted-foreground">Securely pay with your card</div>
                  </div>
                </div>
                <Button variant="outline">Pay with Razorpay</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function CreditCardIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}
